#!/usr/bin/env python3
"""
Generate 15 test cases per problem with 'sample' flag.
First 3 are sample:true (visible), remaining 12 are sample:false (hidden).
Outputs SQL UPDATE statements to patch data.sql.
"""
import json

# Each entry: title -> list of 15 {input, expected} dicts
PROBLEMS = {
    "Two Sum": [
        {"input":"[2,7,11,15]\\n9","expected":"[0, 1]"},
        {"input":"[3,2,4]\\n6","expected":"[1, 2]"},
        {"input":"[3,3]\\n6","expected":"[0, 1]"},
        {"input":"[1,5,3,7]\\n8","expected":"[1, 3]"},
        {"input":"[4,6,1]\\n5","expected":"[0, 2]"},
        {"input":"[0,4,3,0]\\n0","expected":"[0, 3]"},
        {"input":"[2,2]\\n4","expected":"[0, 1]"},
        {"input":"[1,2,3,4,5]\\n9","expected":"[3, 4]"},
        {"input":"[10,20,30]\\n50","expected":"[1, 2]"},
        {"input":"[-1,0,1]\\n0","expected":"[0, 2]"},
        {"input":"[100,200]\\n300","expected":"[0, 1]"},
        {"input":"[5,10,15,20]\\n25","expected":"[1, 2]"}, # 10+15
        {"input":"[1,3,5,7,9]\\n10","expected":"[0, 4]"},
        {"input":"[6,6]\\n12","expected":"[0, 1]"},
        {"input":"[1,4,5,6]\\n10","expected":"[1, 3]"},
    ],
    "Reverse String": [
        {"input":"hello","expected":"olleh"},
        {"input":"world","expected":"dlrow"},
        {"input":"abcd","expected":"dcba"},
        {"input":"a","expected":"a"},
        {"input":"ab","expected":"ba"},
        {"input":"racecar","expected":"racecar"},
        {"input":"python","expected":"nohtyp"},
        {"input":"12345","expected":"54321"},
        {"input":"OpenAI","expected":"IAnepO"},
        {"input":"abcdef","expected":"fedcba"},
        {"input":"zzz","expected":"zzz"},
        {"input":"code","expected":"edoc"},
        {"input":"test","expected":"tset"},
        {"input":"hello world","expected":"dlrow olleh"},
        {"input":"madam","expected":"madam"},
    ],
    "FizzBuzz": [
        {"input":"5","expected":"1\\n2\\nFizz\\n4\\nBuzz"},
        {"input":"15","expected":"1\\n2\\nFizz\\n4\\nBuzz\\nFizz\\n7\\n8\\nFizz\\nBuzz\\n11\\nFizz\\n13\\n14\\nFizzBuzz"},
        {"input":"3","expected":"1\\n2\\nFizz"},
        {"input":"1","expected":"1"},
        {"input":"2","expected":"1\\n2"},
        {"input":"6","expected":"1\\n2\\nFizz\\n4\\nBuzz\\nFizz"},
        {"input":"10","expected":"1\\n2\\nFizz\\n4\\nBuzz\\nFizz\\n7\\n8\\nFizz\\nBuzz"},
        {"input":"4","expected":"1\\n2\\nFizz\\n4"},
        {"input":"7","expected":"1\\n2\\nFizz\\n4\\nBuzz\\nFizz\\n7"},
        {"input":"9","expected":"1\\n2\\nFizz\\n4\\nBuzz\\nFizz\\n7\\n8\\nFizz"},
        {"input":"11","expected":"1\\n2\\nFizz\\n4\\nBuzz\\nFizz\\n7\\n8\\nFizz\\nBuzz\\n11"},
        {"input":"12","expected":"1\\n2\\nFizz\\n4\\nBuzz\\nFizz\\n7\\n8\\nFizz\\nBuzz\\n11\\nFizz"},
        {"input":"13","expected":"1\\n2\\nFizz\\n4\\nBuzz\\nFizz\\n7\\n8\\nFizz\\nBuzz\\n11\\nFizz\\n13"},
        {"input":"14","expected":"1\\n2\\nFizz\\n4\\nBuzz\\nFizz\\n7\\n8\\nFizz\\nBuzz\\n11\\nFizz\\n13\\n14"},
        {"input":"8","expected":"1\\n2\\nFizz\\n4\\nBuzz\\nFizz\\n7\\n8"},
    ],
    "Valid Parentheses": [
        {"input":"()[]{}","expected":"True"},
        {"input":"(]","expected":"False"},
        {"input":"([)]","expected":"False"},
        {"input":"()","expected":"True"},
        {"input":"{}","expected":"True"},
        {"input":"[]","expected":"True"},
        {"input":"((()))","expected":"True"},
        {"input":"(","expected":"False"},
        {"input":")","expected":"False"},
        {"input":"({[]})","expected":"True"},
        {"input":"[{()}]","expected":"True"},
        {"input":"","expected":"True"},
        {"input":"(()","expected":"False"},
        {"input":"({})[()]","expected":"True"},
        {"input":"([{}])()","expected":"True"},
    ],
    "Merge Sorted Arrays": [
        {"input":"[1,3,5]\\n[2,4,6]","expected":"[1, 2, 3, 4, 5, 6]"},
        {"input":"[1,2]\\n[3,4]","expected":"[1, 2, 3, 4]"},
        {"input":"[1]\\n[2]","expected":"[1, 2]"},
        {"input":"[]\\n[1,2,3]","expected":"[1, 2, 3]"},
        {"input":"[1,2,3]\\n[]","expected":"[1, 2, 3]"},
        {"input":"[1,1,1]\\n[1,1,1]","expected":"[1, 1, 1, 1, 1, 1]"},
        {"input":"[5,10,15]\\n[3,7,12]","expected":"[3, 5, 7, 10, 12, 15]"},
        {"input":"[1,3,5,7]\\n[2,4,6,8]","expected":"[1, 2, 3, 4, 5, 6, 7, 8]"},
        {"input":"[100]\\n[1]","expected":"[1, 100]"},
        {"input":"[2,4]\\n[1,3,5]","expected":"[1, 2, 3, 4, 5]"},
        {"input":"[0,0]\\n[0,0]","expected":"[0, 0, 0, 0]"},
        {"input":"[10,20,30]\\n[5,15,25]","expected":"[5, 10, 15, 20, 25, 30]"},
        {"input":"[-3,-1]\\n[-2,0]","expected":"[-3, -2, -1, 0]"},
        {"input":"[1,2,3,4,5]\\n[6,7,8,9,10]","expected":"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]"},
        {"input":"[50]\\n[25,75]","expected":"[25, 50, 75]"},
    ],
    "Binary Search": [
        {"input":"[1,3,5,7,9]\\n5","expected":"2"},
        {"input":"[1,3,5,7,9]\\n2","expected":"-1"},
        {"input":"[1,2,3,4,5]\\n1","expected":"0"},
        {"input":"[1,2,3,4,5]\\n5","expected":"4"},
        {"input":"[10,20,30,40,50]\\n30","expected":"2"},
        {"input":"[1]\\n1","expected":"0"},
        {"input":"[1]\\n2","expected":"-1"},
        {"input":"[2,4,6,8,10]\\n8","expected":"3"},
        {"input":"[1,3,5,7,9,11]\\n11","expected":"5"},
        {"input":"[100,200,300]\\n100","expected":"0"},
        {"input":"[5,15,25,35,45]\\n45","expected":"4"},
        {"input":"[1,2,3]\\n4","expected":"-1"},
        {"input":"[10,20,30,40]\\n10","expected":"0"},
        {"input":"[3,6,9,12,15]\\n9","expected":"2"},
        {"input":"[1,5,10,15,20,25]\\n15","expected":"3"},
    ],
    "Longest Common Subsequence": [
        {"input":"abcde\\nace","expected":"3"},
        {"input":"abc\\nabc","expected":"3"},
        {"input":"abc\\ndef","expected":"0"},
        {"input":"abcd\\nabd","expected":"3"},
        {"input":"a\\na","expected":"1"},
        {"input":"a\\nb","expected":"0"},
        {"input":"abcdef\\nacf","expected":"3"},
        {"input":"xyz\\nxyz","expected":"3"},
        {"input":"abcde\\nbce","expected":"3"},
        {"input":"abc\\n","expected":"0"},
        {"input":"pqrs\\nprt","expected":"2"},
        {"input":"aab\\nazb","expected":"2"},
        {"input":"bl\\nyby","expected":"1"},
        {"input":"abcba\\nabcbcba","expected":"5"},
        {"input":"oxcpqrsvwf\\nshmtulqrypy","expected":"2"},
    ],
    "Median of Two Sorted Arrays": [
        {"input":"[1,3]\\n[2]","expected":"2.0"},
        {"input":"[1,2]\\n[3,4]","expected":"2.5"},
        {"input":"[0,0]\\n[0,0]","expected":"0.0"},
        {"input":"[1]\\n[2,3]","expected":"2.0"},
        {"input":"[1,2,3]\\n[4,5,6]","expected":"3.5"},
        {"input":"[1]\\n[1]","expected":"1.0"},
        {"input":"[2]\\n[1,3,4]","expected":"2.5"},
        {"input":"[1,3,5]\\n[2,4,6]","expected":"3.5"},
        {"input":"[1,2]\\n[1,2]","expected":"1.5"},
        {"input":"[3]\\n[1,2]","expected":"2.0"},
        {"input":"[1,5,9]\\n[2,6,10]","expected":"5.5"},
        {"input":"[100]\\n[200]","expected":"150.0"},
        {"input":"[1,2,3,4]\\n[5,6,7,8]","expected":"4.5"},
        {"input":"[10,20]\\n[15,25]","expected":"17.5"},
        {"input":"[1]\\n[2,3,4,5]","expected":"3.0"},
    ],
    "Find Maximum Number": [
        {"input":"[1,5,3,9,2]","expected":"9"},
        {"input":"[10,20,5]","expected":"20"},
        {"input":"[1]","expected":"1"},
        {"input":"[3,3,3]","expected":"3"},
        {"input":"[-1,-5,-3]","expected":"-1"},
        {"input":"[100,200,300]","expected":"300"},
        {"input":"[0,0,0,0]","expected":"0"},
        {"input":"[7]","expected":"7"},
        {"input":"[5,4,3,2,1]","expected":"5"},
        {"input":"[1,2,3,4,5]","expected":"5"},
        {"input":"[-10,0,10]","expected":"10"},
        {"input":"[999,1000,998]","expected":"1000"},
        {"input":"[42,17,88,3]","expected":"88"},
        {"input":"[50,50]","expected":"50"},
        {"input":"[1,100,1]","expected":"100"},
    ],
    "Sum of Array": [
        {"input":"[1,2,3,4]","expected":"10"},
        {"input":"[5,5,5]","expected":"15"},
        {"input":"[0]","expected":"0"},
        {"input":"[10,20,30]","expected":"60"},
        {"input":"[1]","expected":"1"},
        {"input":"[-1,1]","expected":"0"},
        {"input":"[100,200,300]","expected":"600"},
        {"input":"[7,3]","expected":"10"},
        {"input":"[0,0,0]","expected":"0"},
        {"input":"[1,2,3,4,5]","expected":"15"},
        {"input":"[10]","expected":"10"},
        {"input":"[50,50,50,50]","expected":"200"},
        {"input":"[-5,-3,-2]","expected":"-10"},
        {"input":"[99,1]","expected":"100"},
        {"input":"[1,1,1,1,1,1,1,1,1,1]","expected":"10"},
    ],
    "Check Even or Odd": [
        {"input":"7","expected":"Odd"},
        {"input":"4","expected":"Even"},
        {"input":"0","expected":"Even"},
        {"input":"1","expected":"Odd"},
        {"input":"2","expected":"Even"},
        {"input":"100","expected":"Even"},
        {"input":"99","expected":"Odd"},
        {"input":"13","expected":"Odd"},
        {"input":"50","expected":"Even"},
        {"input":"1001","expected":"Odd"},
        {"input":"256","expected":"Even"},
        {"input":"3","expected":"Odd"},
        {"input":"10","expected":"Even"},
        {"input":"555","expected":"Odd"},
        {"input":"1024","expected":"Even"},
    ],
    "Count Vowels": [
        {"input":"hello","expected":"2"},
        {"input":"aeiou","expected":"5"},
        {"input":"bcdfg","expected":"0"},
        {"input":"a","expected":"1"},
        {"input":"xyz","expected":"0"},
        {"input":"programming","expected":"3"},
        {"input":"AEIOU","expected":"5"},
        {"input":"python","expected":"1"},
        {"input":"beautiful","expected":"5"},
        {"input":"rhythm","expected":"0"},
        {"input":"education","expected":"5"},
        {"input":"b","expected":"0"},
        {"input":"umbrella","expected":"3"},
        {"input":"queue","expected":"4"},
        {"input":"strength","expected":"1"},
    ],
    "Palindrome String": [
        {"input":"madam","expected":"True"},
        {"input":"hello","expected":"False"},
        {"input":"a","expected":"True"},
        {"input":"racecar","expected":"True"},
        {"input":"ab","expected":"False"},
        {"input":"aba","expected":"True"},
        {"input":"abba","expected":"True"},
        {"input":"abc","expected":"False"},
        {"input":"level","expected":"True"},
        {"input":"noon","expected":"True"},
        {"input":"kayak","expected":"True"},
        {"input":"world","expected":"False"},
        {"input":"deed","expected":"True"},
        {"input":"python","expected":"False"},
        {"input":"civic","expected":"True"},
    ],
    "Find Minimum": [
        {"input":"[4,2,7,1]","expected":"1"},
        {"input":"[10,5,15]","expected":"5"},
        {"input":"[5]","expected":"5"},
        {"input":"[3,3,3]","expected":"3"},
        {"input":"[-1,-5,-3]","expected":"-5"},
        {"input":"[100,200,300]","expected":"100"},
        {"input":"[0,0,0,0]","expected":"0"},
        {"input":"[9,8,7,6,5]","expected":"5"},
        {"input":"[1,2,3]","expected":"1"},
        {"input":"[-10,0,10]","expected":"-10"},
        {"input":"[50]","expected":"50"},
        {"input":"[999,1,1000]","expected":"1"},
        {"input":"[42,17,88,3]","expected":"3"},
        {"input":"[50,50]","expected":"50"},
        {"input":"[7,2,9,4]","expected":"2"},
    ],
    "Factorial": [
        {"input":"5","expected":"120"},
        {"input":"0","expected":"1"},
        {"input":"3","expected":"6"},
        {"input":"1","expected":"1"},
        {"input":"2","expected":"2"},
        {"input":"4","expected":"24"},
        {"input":"6","expected":"720"},
        {"input":"7","expected":"5040"},
        {"input":"8","expected":"40320"},
        {"input":"9","expected":"362880"},
        {"input":"10","expected":"3628800"},
        {"input":"11","expected":"39916800"},
        {"input":"12","expected":"479001600"},
        {"input":"13","expected":"6227020800"},
        {"input":"14","expected":"87178291200"},
    ],
    "Fibonacci Nth": [
        {"input":"6","expected":"8"},
        {"input":"1","expected":"1"},
        {"input":"5","expected":"5"},
        {"input":"0","expected":"0"},
        {"input":"2","expected":"1"},
        {"input":"3","expected":"2"},
        {"input":"4","expected":"3"},
        {"input":"7","expected":"13"},
        {"input":"8","expected":"21"},
        {"input":"9","expected":"34"},
        {"input":"10","expected":"55"},
        {"input":"11","expected":"89"},
        {"input":"12","expected":"144"},
        {"input":"13","expected":"233"},
        {"input":"14","expected":"377"},
    ],
    "Reverse Array": [
        {"input":"[1,2,3]","expected":"[3, 2, 1]"},
        {"input":"[10,20]","expected":"[20, 10]"},
        {"input":"[5]","expected":"[5]"},
        {"input":"[1,2,3,4,5]","expected":"[5, 4, 3, 2, 1]"},
        {"input":"[0,0,0]","expected":"[0, 0, 0]"},
        {"input":"[9,8,7,6]","expected":"[6, 7, 8, 9]"},
        {"input":"[100]","expected":"[100]"},
        {"input":"[-1,-2,-3]","expected":"[-3, -2, -1]"},
        {"input":"[1,1,1,1]","expected":"[1, 1, 1, 1]"},
        {"input":"[3,6,9]","expected":"[9, 6, 3]"},
        {"input":"[2,4]","expected":"[4, 2]"},
        {"input":"[7,14,21,28]","expected":"[28, 21, 14, 7]"},
        {"input":"[50,40,30,20,10]","expected":"[10, 20, 30, 40, 50]"},
        {"input":"[1,3,5,7,9]","expected":"[9, 7, 5, 3, 1]"},
        {"input":"[11,22,33]","expected":"[33, 22, 11]"},
    ],
    "Count Digits": [
        {"input":"12345","expected":"5"},
        {"input":"100","expected":"3"},
        {"input":"9","expected":"1"},
        {"input":"0","expected":"1"},
        {"input":"10","expected":"2"},
        {"input":"99999","expected":"5"},
        {"input":"1000000","expected":"7"},
        {"input":"42","expected":"2"},
        {"input":"7","expected":"1"},
        {"input":"555","expected":"3"},
        {"input":"1234567890","expected":"10"},
        {"input":"11","expected":"2"},
        {"input":"123","expected":"3"},
        {"input":"9999","expected":"4"},
        {"input":"50","expected":"2"},
    ],
    "Sum of Digits": [
        {"input":"123","expected":"6"},
        {"input":"100","expected":"1"},
        {"input":"555","expected":"15"},
        {"input":"0","expected":"0"},
        {"input":"9","expected":"9"},
        {"input":"99","expected":"18"},
        {"input":"12","expected":"3"},
        {"input":"999","expected":"27"},
        {"input":"1001","expected":"2"},
        {"input":"45","expected":"9"},
        {"input":"111","expected":"3"},
        {"input":"246","expected":"12"},
        {"input":"789","expected":"24"},
        {"input":"50","expected":"5"},
        {"input":"321","expected":"6"},
    ],
    "Check Prime": [
        {"input":"7","expected":"True"},
        {"input":"4","expected":"False"},
        {"input":"2","expected":"True"},
        {"input":"1","expected":"False"},
        {"input":"3","expected":"True"},
        {"input":"9","expected":"False"},
        {"input":"11","expected":"True"},
        {"input":"13","expected":"True"},
        {"input":"15","expected":"False"},
        {"input":"17","expected":"True"},
        {"input":"19","expected":"True"},
        {"input":"20","expected":"False"},
        {"input":"23","expected":"True"},
        {"input":"25","expected":"False"},
        {"input":"29","expected":"True"},
    ],
    "Largest of Three": [
        {"input":"3 7 5","expected":"7"},
        {"input":"10 5 15","expected":"15"},
        {"input":"1 1 1","expected":"1"},
        {"input":"0 0 0","expected":"0"},
        {"input":"100 200 300","expected":"300"},
        {"input":"-1 -2 -3","expected":"-1"},
        {"input":"5 5 3","expected":"5"},
        {"input":"10 10 10","expected":"10"},
        {"input":"99 100 98","expected":"100"},
        {"input":"1 2 3","expected":"3"},
        {"input":"50 25 75","expected":"75"},
        {"input":"7 3 9","expected":"9"},
        {"input":"1000 999 998","expected":"1000"},
        {"input":"0 1 -1","expected":"1"},
        {"input":"42 42 41","expected":"42"},
    ],
    "String Length": [
        {"input":"hello","expected":"5"},
        {"input":"world","expected":"5"},
        {"input":"a","expected":"1"},
        {"input":"","expected":"0"},
        {"input":"ab","expected":"2"},
        {"input":"python","expected":"6"},
        {"input":"programming","expected":"11"},
        {"input":"test","expected":"4"},
        {"input":"hi","expected":"2"},
        {"input":"abcdef","expected":"6"},
        {"input":"123","expected":"3"},
        {"input":"x","expected":"1"},
        {"input":"longer string","expected":"13"},
        {"input":"code","expected":"4"},
        {"input":"abcdefghij","expected":"10"},
    ],
    "Uppercase String": [
        {"input":"hello","expected":"HELLO"},
        {"input":"World","expected":"WORLD"},
        {"input":"abc","expected":"ABC"},
        {"input":"a","expected":"A"},
        {"input":"python","expected":"PYTHON"},
        {"input":"test","expected":"TEST"},
        {"input":"HeLLo","expected":"HELLO"},
        {"input":"xyz","expected":"XYZ"},
        {"input":"code","expected":"CODE"},
        {"input":"java","expected":"JAVA"},
        {"input":"hi","expected":"HI"},
        {"input":"ALREADY","expected":"ALREADY"},
        {"input":"open","expected":"OPEN"},
        {"input":"data","expected":"DATA"},
        {"input":"fun","expected":"FUN"},
    ],
    "Lowercase String": [
        {"input":"HELLO","expected":"hello"},
        {"input":"World","expected":"world"},
        {"input":"ABC","expected":"abc"},
        {"input":"A","expected":"a"},
        {"input":"PYTHON","expected":"python"},
        {"input":"TEST","expected":"test"},
        {"input":"HeLLo","expected":"hello"},
        {"input":"XYZ","expected":"xyz"},
        {"input":"CODE","expected":"code"},
        {"input":"JAVA","expected":"java"},
        {"input":"HI","expected":"hi"},
        {"input":"already","expected":"already"},
        {"input":"OPEN","expected":"open"},
        {"input":"DATA","expected":"data"},
        {"input":"FUN","expected":"fun"},
    ],
    "Square of Numbers": [
        {"input":"5","expected":"25"},
        {"input":"0","expected":"0"},
        {"input":"3","expected":"9"},
        {"input":"1","expected":"1"},
        {"input":"10","expected":"100"},
        {"input":"7","expected":"49"},
        {"input":"12","expected":"144"},
        {"input":"2","expected":"4"},
        {"input":"4","expected":"16"},
        {"input":"6","expected":"36"},
        {"input":"8","expected":"64"},
        {"input":"9","expected":"81"},
        {"input":"11","expected":"121"},
        {"input":"15","expected":"225"},
        {"input":"20","expected":"400"},
    ],
    "Cube of Numbers": [
        {"input":"3","expected":"27"},
        {"input":"0","expected":"0"},
        {"input":"2","expected":"8"},
        {"input":"1","expected":"1"},
        {"input":"5","expected":"125"},
        {"input":"4","expected":"64"},
        {"input":"6","expected":"216"},
        {"input":"7","expected":"343"},
        {"input":"10","expected":"1000"},
        {"input":"8","expected":"512"},
        {"input":"9","expected":"729"},
        {"input":"11","expected":"1331"},
        {"input":"12","expected":"1728"},
        {"input":"15","expected":"3375"},
        {"input":"20","expected":"8000"},
    ],
    "Swap Two Numbers": [
        {"input":"3 5","expected":"5 3"},
        {"input":"10 20","expected":"20 10"},
        {"input":"0 0","expected":"0 0"},
        {"input":"1 2","expected":"2 1"},
        {"input":"-1 1","expected":"1 -1"},
        {"input":"100 200","expected":"200 100"},
        {"input":"7 3","expected":"3 7"},
        {"input":"50 50","expected":"50 50"},
        {"input":"99 1","expected":"1 99"},
        {"input":"5 10","expected":"10 5"},
        {"input":"42 24","expected":"24 42"},
        {"input":"0 1","expected":"1 0"},
        {"input":"1000 2000","expected":"2000 1000"},
        {"input":"13 31","expected":"31 13"},
        {"input":"8 4","expected":"4 8"},
    ],
    "Is Leap Year Check": [
        {"input":"2000","expected":"True"},
        {"input":"1900","expected":"False"},
        {"input":"2024","expected":"True"},
        {"input":"2023","expected":"False"},
        {"input":"2100","expected":"False"},
        {"input":"1600","expected":"True"},
        {"input":"2004","expected":"True"},
        {"input":"1999","expected":"False"},
        {"input":"2020","expected":"True"},
        {"input":"1800","expected":"False"},
        {"input":"400","expected":"True"},
        {"input":"100","expected":"False"},
        {"input":"2016","expected":"True"},
        {"input":"2019","expected":"False"},
        {"input":"2400","expected":"True"},
    ],
    "Sum of First N Numbers": [
        {"input":"5","expected":"15"},
        {"input":"10","expected":"55"},
        {"input":"1","expected":"1"},
        {"input":"0","expected":"0"},
        {"input":"3","expected":"6"},
        {"input":"100","expected":"5050"},
        {"input":"7","expected":"28"},
        {"input":"20","expected":"210"},
        {"input":"50","expected":"1275"},
        {"input":"2","expected":"3"},
        {"input":"4","expected":"10"},
        {"input":"15","expected":"120"},
        {"input":"25","expected":"325"},
        {"input":"6","expected":"21"},
        {"input":"8","expected":"36"},
    ],
    "Power of Number": [
        {"input":"2 3","expected":"8"},
        {"input":"5 2","expected":"25"},
        {"input":"10 0","expected":"1"},
        {"input":"3 3","expected":"27"},
        {"input":"2 10","expected":"1024"},
        {"input":"1 100","expected":"1"},
        {"input":"7 2","expected":"49"},
        {"input":"4 3","expected":"64"},
        {"input":"2 0","expected":"1"},
        {"input":"5 3","expected":"125"},
        {"input":"6 2","expected":"36"},
        {"input":"3 4","expected":"81"},
        {"input":"2 5","expected":"32"},
        {"input":"9 2","expected":"81"},
        {"input":"10 3","expected":"1000"},
    ],
    "Reverse Number": [
        {"input":"123","expected":"321"},
        {"input":"100","expected":"1"},
        {"input":"5","expected":"5"},
        {"input":"1234","expected":"4321"},
        {"input":"0","expected":"0"},
        {"input":"10","expected":"1"},
        {"input":"999","expected":"999"},
        {"input":"1001","expected":"1001"},
        {"input":"50","expected":"5"},
        {"input":"12","expected":"21"},
        {"input":"54321","expected":"12345"},
        {"input":"7","expected":"7"},
        {"input":"200","expected":"2"},
        {"input":"9876","expected":"6789"},
        {"input":"1010","expected":"101"},
    ],
    "Check Armstrong Number": [
        {"input":"153","expected":"True"},
        {"input":"370","expected":"True"},
        {"input":"100","expected":"False"},
        {"input":"1","expected":"True"},
        {"input":"0","expected":"True"},
        {"input":"371","expected":"True"},
        {"input":"407","expected":"True"},
        {"input":"10","expected":"False"},
        {"input":"9","expected":"True"},
        {"input":"123","expected":"False"},
        {"input":"5","expected":"True"},
        {"input":"200","expected":"False"},
        {"input":"8","expected":"True"},
        {"input":"999","expected":"False"},
        {"input":"2","expected":"True"},
    ],
    "GCD of Two Numbers": [
        {"input":"12 8","expected":"4"},
        {"input":"100 75","expected":"25"},
        {"input":"7 3","expected":"1"},
        {"input":"6 6","expected":"6"},
        {"input":"10 5","expected":"5"},
        {"input":"1 1","expected":"1"},
        {"input":"24 36","expected":"12"},
        {"input":"15 10","expected":"5"},
        {"input":"21 14","expected":"7"},
        {"input":"48 18","expected":"6"},
        {"input":"100 10","expected":"10"},
        {"input":"9 6","expected":"3"},
        {"input":"17 13","expected":"1"},
        {"input":"56 98","expected":"14"},
        {"input":"81 27","expected":"27"},
    ],
    "LCM of Two Numbers": [
        {"input":"4 6","expected":"12"},
        {"input":"3 5","expected":"15"},
        {"input":"7 3","expected":"21"},
        {"input":"1 1","expected":"1"},
        {"input":"6 6","expected":"6"},
        {"input":"2 3","expected":"6"},
        {"input":"12 8","expected":"24"},
        {"input":"10 15","expected":"30"},
        {"input":"5 7","expected":"35"},
        {"input":"4 10","expected":"20"},
        {"input":"9 6","expected":"18"},
        {"input":"8 12","expected":"24"},
        {"input":"15 20","expected":"60"},
        {"input":"3 9","expected":"9"},
        {"input":"14 21","expected":"42"},
    ],
    "Multiplication Table": [
        {"input":"5","expected":"5 10 15 20 25 30 35 40 45 50"},
        {"input":"3","expected":"3 6 9 12 15 18 21 24 27 30"},
        {"input":"1","expected":"1 2 3 4 5 6 7 8 9 10"},
        {"input":"2","expected":"2 4 6 8 10 12 14 16 18 20"},
        {"input":"7","expected":"7 14 21 28 35 42 49 56 63 70"},
        {"input":"10","expected":"10 20 30 40 50 60 70 80 90 100"},
        {"input":"4","expected":"4 8 12 16 20 24 28 32 36 40"},
        {"input":"6","expected":"6 12 18 24 30 36 42 48 54 60"},
        {"input":"8","expected":"8 16 24 32 40 48 56 64 72 80"},
        {"input":"9","expected":"9 18 27 36 45 54 63 72 81 90"},
        {"input":"11","expected":"11 22 33 44 55 66 77 88 99 110"},
        {"input":"12","expected":"12 24 36 48 60 72 84 96 108 120"},
        {"input":"15","expected":"15 30 45 60 75 90 105 120 135 150"},
        {"input":"20","expected":"20 40 60 80 100 120 140 160 180 200"},
        {"input":"13","expected":"13 26 39 52 65 78 91 104 117 130"},
    ],
    "Sum of Even Numbers": [
        {"input":"[1,2,3,4,5,6]","expected":"12"},
        {"input":"[2,4,6]","expected":"12"},
        {"input":"[1,3,5]","expected":"0"},
        {"input":"[10,20,30]","expected":"60"},
        {"input":"[0]","expected":"0"},
        {"input":"[1]","expected":"0"},
        {"input":"[2]","expected":"2"},
        {"input":"[1,2,3,4]","expected":"6"},
        {"input":"[100,200]","expected":"300"},
        {"input":"[7,8,9,10]","expected":"18"},
        {"input":"[0,0,0]","expected":"0"},
        {"input":"[11,22,33,44]","expected":"66"},
        {"input":"[5,10,15,20]","expected":"30"},
        {"input":"[1,2]","expected":"2"},
        {"input":"[4,4,4]","expected":"12"},
    ],
    "Sum of Odd Numbers": [
        {"input":"[1,2,3,4,5]","expected":"9"},
        {"input":"[1,3,5]","expected":"9"},
        {"input":"[2,4,6]","expected":"0"},
        {"input":"[10,11,12,13]","expected":"24"},
        {"input":"[0]","expected":"0"},
        {"input":"[1]","expected":"1"},
        {"input":"[3]","expected":"3"},
        {"input":"[1,2,3,4]","expected":"4"},
        {"input":"[99,100]","expected":"99"},
        {"input":"[7,8,9,10]","expected":"16"},
        {"input":"[0,0,0]","expected":"0"},
        {"input":"[11,22,33,44]","expected":"44"},
        {"input":"[5,10,15,20]","expected":"20"},
        {"input":"[1,2]","expected":"1"},
        {"input":"[3,5,7]","expected":"15"},
    ],
    "Count Even Numbers in Array": [
        {"input":"[1,2,3,4,5,6]","expected":"3"},
        {"input":"[2,4,6,8]","expected":"4"},
        {"input":"[1,3,5]","expected":"0"},
        {"input":"[10]","expected":"1"},
        {"input":"[1]","expected":"0"},
        {"input":"[0]","expected":"1"},
        {"input":"[2,3,4,5]","expected":"2"},
        {"input":"[100,200,300]","expected":"3"},
        {"input":"[7,8,9,10]","expected":"2"},
        {"input":"[1,2,3,4,5,6,7,8]","expected":"4"},
        {"input":"[11,22,33,44,55]","expected":"2"},
        {"input":"[0,0,0]","expected":"3"},
        {"input":"[1,1,1]","expected":"0"},
        {"input":"[2,2,2]","expected":"3"},
        {"input":"[5,10,15,20]","expected":"2"},
    ],
    "Count Odd Numbers": [
        {"input":"[1,2,3,4,5]","expected":"3"},
        {"input":"[1,3,5,7]","expected":"4"},
        {"input":"[2,4,6]","expected":"0"},
        {"input":"[10]","expected":"0"},
        {"input":"[1]","expected":"1"},
        {"input":"[0]","expected":"0"},
        {"input":"[2,3,4,5]","expected":"2"},
        {"input":"[100,201,300]","expected":"1"},
        {"input":"[7,8,9,10]","expected":"2"},
        {"input":"[1,2,3,4,5,6,7,8]","expected":"4"},
        {"input":"[11,22,33,44,55]","expected":"3"},
        {"input":"[0,0,0]","expected":"0"},
        {"input":"[1,1,1]","expected":"3"},
        {"input":"[3,3,3]","expected":"3"},
        {"input":"[5,10,15,20]","expected":"2"},
    ],
    "Find Second Largest": [
        {"input":"[1,2,3,4,5]","expected":"4"},
        {"input":"[10,20,30]","expected":"20"},
        {"input":"[5,5,5]","expected":"-1"},
        {"input":"[1,2]","expected":"1"},
        {"input":"[100,50,75]","expected":"75"},
        {"input":"[3,1,2]","expected":"2"},
        {"input":"[9,8,7,6]","expected":"8"},
        {"input":"[1,1,2]","expected":"1"},
        {"input":"[5,3,5,1]","expected":"3"},
        {"input":"[10,10,10]","expected":"-1"},
        {"input":"[7,7,8]","expected":"7"},
        {"input":"[1,3]","expected":"1"},
        {"input":"[50,40,30,20]","expected":"40"},
        {"input":"[99,100]","expected":"99"},
        {"input":"[2,4,6,8,10]","expected":"8"},
    ],
    "Find Average": [
        {"input":"[10,20,30]","expected":"20.0"},
        {"input":"[5,5,5]","expected":"5.0"},
        {"input":"[1,2,3,4]","expected":"2.5"},
        {"input":"[0]","expected":"0.0"},
        {"input":"[100]","expected":"100.0"},
        {"input":"[1,2]","expected":"1.5"},
        {"input":"[10,20]","expected":"15.0"},
        {"input":"[3,6,9]","expected":"6.0"},
        {"input":"[1,1,1,1]","expected":"1.0"},
        {"input":"[50,100]","expected":"75.0"},
        {"input":"[7,8,9]","expected":"8.0"},
        {"input":"[2,4,6,8,10]","expected":"6.0"},
        {"input":"[0,0,0]","expected":"0.0"},
        {"input":"[25,75]","expected":"50.0"},
        {"input":"[1,3,5,7,9]","expected":"5.0"},
    ],
    "Check Sorted Array": [
        {"input":"[1,2,3,4,5]","expected":"True"},
        {"input":"[5,4,3,2,1]","expected":"False"},
        {"input":"[1]","expected":"True"},
        {"input":"[1,1,1]","expected":"True"},
        {"input":"[1,3,2]","expected":"False"},
        {"input":"[1,2]","expected":"True"},
        {"input":"[2,1]","expected":"False"},
        {"input":"[0,0,0,0]","expected":"True"},
        {"input":"[1,2,3]","expected":"True"},
        {"input":"[3,2,1]","expected":"False"},
        {"input":"[10,20,30,40]","expected":"True"},
        {"input":"[1,2,2,3]","expected":"True"},
        {"input":"[5,10,3]","expected":"False"},
        {"input":"[100,200,300]","expected":"True"},
        {"input":"[9,8]","expected":"False"},
    ],
    "Merge Two Arrays": [
        {"input":"[1,2,3]\\n[4,5,6]","expected":"[1, 2, 3, 4, 5, 6]"},
        {"input":"[1]\\n[2]","expected":"[1, 2]"},
        {"input":"[]\\n[1,2]","expected":"[1, 2]"},
        {"input":"[1,2]\\n[]","expected":"[1, 2]"},
        {"input":"[5,10]\\n[15,20]","expected":"[5, 10, 15, 20]"},
        {"input":"[0]\\n[0]","expected":"[0, 0]"},
        {"input":"[1,3,5]\\n[2,4,6]","expected":"[1, 3, 5, 2, 4, 6]"},
        {"input":"[100]\\n[200,300]","expected":"[100, 200, 300]"},
        {"input":"[7,8,9]\\n[10,11,12]","expected":"[7, 8, 9, 10, 11, 12]"},
        {"input":"[1,1]\\n[1,1]","expected":"[1, 1, 1, 1]"},
        {"input":"[-1]\\n[1]","expected":"[-1, 1]"},
        {"input":"[3,6]\\n[9,12]","expected":"[3, 6, 9, 12]"},
        {"input":"[50,60,70]\\n[80]","expected":"[50, 60, 70, 80]"},
        {"input":"[1,2,3,4]\\n[5,6,7,8]","expected":"[1, 2, 3, 4, 5, 6, 7, 8]"},
        {"input":"[10]\\n[20,30,40]","expected":"[10, 20, 30, 40]"},
    ],
    "Remove Duplicates": [
        {"input":"[1,2,2,3,3,4]","expected":"[1, 2, 3, 4]"},
        {"input":"[1,1,1]","expected":"[1]"},
        {"input":"[1,2,3]","expected":"[1, 2, 3]"},
        {"input":"[5]","expected":"[5]"},
        {"input":"[1,2,1,2]","expected":"[1, 2]"},
        {"input":"[3,3,3,3]","expected":"[3]"},
        {"input":"[10,20,10,30,20]","expected":"[10, 20, 30]"},
        {"input":"[0,0,1,1,2,2]","expected":"[0, 1, 2]"},
        {"input":"[5,4,3,2,1]","expected":"[5, 4, 3, 2, 1]"},
        {"input":"[7,7,8,8,9]","expected":"[7, 8, 9]"},
        {"input":"[1]","expected":"[1]"},
        {"input":"[2,2]","expected":"[2]"},
        {"input":"[100,200,100]","expected":"[100, 200]"},
        {"input":"[1,2,3,4,5]","expected":"[1, 2, 3, 4, 5]"},
        {"input":"[9,9,9,8,7]","expected":"[9, 8, 7]"},
    ],
    "Find Index of Element": [
        {"input":"[1,2,3,4,5]\\n3","expected":"2"},
        {"input":"[10,20,30]\\n20","expected":"1"},
        {"input":"[5,10,15]\\n5","expected":"0"},
        {"input":"[1,2,3]\\n4","expected":"-1"},
        {"input":"[7]\\n7","expected":"0"},
        {"input":"[1,2,3,4,5]\\n1","expected":"0"},
        {"input":"[1,2,3,4,5]\\n5","expected":"4"},
        {"input":"[10,20,30,40]\\n40","expected":"3"},
        {"input":"[100]\\n50","expected":"-1"},
        {"input":"[3,6,9,12]\\n9","expected":"2"},
        {"input":"[1,1,1]\\n1","expected":"0"},
        {"input":"[5,10,15,20]\\n15","expected":"2"},
        {"input":"[2,4,6,8,10]\\n6","expected":"2"},
        {"input":"[0,0,0]\\n0","expected":"0"},
        {"input":"[50,100]\\n100","expected":"1"},
    ],
    "Count Occurrences": [
        {"input":"[1,2,2,3,3,3]\\n3","expected":"3"},
        {"input":"[1,1,1,1]\\n1","expected":"4"},
        {"input":"[5,10,15]\\n20","expected":"0"},
        {"input":"[0,0,0,0,0]\\n0","expected":"5"},
        {"input":"[1,2,3]\\n2","expected":"1"},
        {"input":"[7]\\n7","expected":"1"},
        {"input":"[1,2,3]\\n4","expected":"0"},
        {"input":"[5,5,5,5]\\n5","expected":"4"},
        {"input":"[10,20,10,30,10]\\n10","expected":"3"},
        {"input":"[1,2,1,2,1]\\n1","expected":"3"},
        {"input":"[3,3,3]\\n3","expected":"3"},
        {"input":"[100,200,300]\\n200","expected":"1"},
        {"input":"[1]\\n1","expected":"1"},
        {"input":"[1]\\n2","expected":"0"},
        {"input":"[2,4,6,8,2]\\n2","expected":"2"},
    ],
    "Multiply All Elements": [
        {"input":"[1,2,3,4]","expected":"24"},
        {"input":"[5,5]","expected":"25"},
        {"input":"[1]","expected":"1"},
        {"input":"[2,3]","expected":"6"},
        {"input":"[10,10,10]","expected":"1000"},
        {"input":"[0,5,10]","expected":"0"},
        {"input":"[1,1,1,1]","expected":"1"},
        {"input":"[2,2,2]","expected":"8"},
        {"input":"[3,3,3]","expected":"27"},
        {"input":"[7,1]","expected":"7"},
        {"input":"[100]","expected":"100"},
        {"input":"[5,4,3,2,1]","expected":"120"},
        {"input":"[2,5]","expected":"10"},
        {"input":"[6,7]","expected":"42"},
        {"input":"[1,2,3,4,5]","expected":"120"},
    ],
    "Check Positive or Negative": [
        {"input":"5","expected":"Positive"},
        {"input":"-3","expected":"Negative"},
        {"input":"0","expected":"Zero"},
        {"input":"1","expected":"Positive"},
        {"input":"-1","expected":"Negative"},
        {"input":"100","expected":"Positive"},
        {"input":"-100","expected":"Negative"},
        {"input":"42","expected":"Positive"},
        {"input":"-42","expected":"Negative"},
        {"input":"999","expected":"Positive"},
        {"input":"-999","expected":"Negative"},
        {"input":"7","expected":"Positive"},
        {"input":"-7","expected":"Negative"},
        {"input":"50","expected":"Positive"},
        {"input":"-50","expected":"Negative"},
    ],
    "Check Anagram": [
        {"input":"listen\\nsilent","expected":"True"},
        {"input":"hello\\nworld","expected":"False"},
        {"input":"abc\\ncba","expected":"True"},
        {"input":"a\\na","expected":"True"},
        {"input":"ab\\nba","expected":"True"},
        {"input":"abc\\nabd","expected":"False"},
        {"input":"rat\\ntar","expected":"True"},
        {"input":"cat\\nact","expected":"True"},
        {"input":"dog\\ngod","expected":"True"},
        {"input":"test\\ntset","expected":"True"},
        {"input":"ab\\nab","expected":"True"},
        {"input":"abc\\ndef","expected":"False"},
        {"input":"aabb\\nbbaa","expected":"True"},
        {"input":"xyz\\nxzy","expected":"True"},
        {"input":"hello\\nhellp","expected":"False"},
    ],
    "Check Substring": [
        {"input":"hello world\\nworld","expected":"True"},
        {"input":"python\\njava","expected":"False"},
        {"input":"abc\\na","expected":"True"},
        {"input":"test\\ntest","expected":"True"},
        {"input":"abc\\nd","expected":"False"},
        {"input":"programming\\ngram","expected":"True"},
        {"input":"hello\\nlo","expected":"True"},
        {"input":"data\\ndat","expected":"True"},
        {"input":"code\\nxyz","expected":"False"},
        {"input":"abcdef\\ncde","expected":"True"},
        {"input":"hello\\nhello world","expected":"False"},
        {"input":"string\\nring","expected":"True"},
        {"input":"test\\nesting","expected":"False"},
        {"input":"abcabc\\nabc","expected":"True"},
        {"input":"xyz\\nxyz","expected":"True"},
    ],
    "Count Character Frequency": [
        {"input":"hello\\nl","expected":"2"},
        {"input":"aabbcc\\na","expected":"2"},
        {"input":"test\\nt","expected":"2"},
        {"input":"abc\\nd","expected":"0"},
        {"input":"aaaa\\na","expected":"4"},
        {"input":"hello\\no","expected":"1"},
        {"input":"programming\\nm","expected":"2"},
        {"input":"banana\\na","expected":"3"},
        {"input":"mississippi\\ns","expected":"4"},
        {"input":"hello\\nh","expected":"1"},
        {"input":"aeiou\\ne","expected":"1"},
        {"input":"xxx\\nx","expected":"3"},
        {"input":"abc\\na","expected":"1"},
        {"input":"abcabc\\nc","expected":"2"},
        {"input":"zzz\\nz","expected":"3"},
    ],
    "Remove Spaces From String": [
        {"input":"hello world","expected":"helloworld"},
        {"input":"a b c","expected":"abc"},
        {"input":"no spaces","expected":"nospaces"},
        {"input":"hello","expected":"hello"},
        {"input":"  leading","expected":"leading"},
        {"input":"trailing  ","expected":"trailing"},
        {"input":"  both  ","expected":"both"},
        {"input":"a  b  c","expected":"abc"},
        {"input":"one two three","expected":"onetwothree"},
        {"input":"x y z","expected":"xyz"},
        {"input":"hi there","expected":"hithere"},
        {"input":"test case","expected":"testcase"},
        {"input":"no  extra  space","expected":"noextraspace"},
        {"input":"a","expected":"a"},
        {"input":"  a  ","expected":"a"},
    ],
    "First Character": [
        {"input":"hello","expected":"h"},
        {"input":"world","expected":"w"},
        {"input":"a","expected":"a"},
        {"input":"Python","expected":"P"},
        {"input":"Java","expected":"J"},
        {"input":"code","expected":"c"},
        {"input":"test","expected":"t"},
        {"input":"xyz","expected":"x"},
        {"input":"ABC","expected":"A"},
        {"input":"123","expected":"1"},
        {"input":"Z","expected":"Z"},
        {"input":"open","expected":"o"},
        {"input":"data","expected":"d"},
        {"input":"fun","expected":"f"},
        {"input":"hi","expected":"h"},
    ],
    "Last Character": [
        {"input":"hello","expected":"o"},
        {"input":"world","expected":"d"},
        {"input":"a","expected":"a"},
        {"input":"Python","expected":"n"},
        {"input":"Java","expected":"a"},
        {"input":"code","expected":"e"},
        {"input":"test","expected":"t"},
        {"input":"xyz","expected":"z"},
        {"input":"ABC","expected":"C"},
        {"input":"123","expected":"3"},
        {"input":"Z","expected":"Z"},
        {"input":"open","expected":"n"},
        {"input":"data","expected":"a"},
        {"input":"fun","expected":"n"},
        {"input":"hi","expected":"i"},
    ],
    "Count Spaces in String": [
        {"input":"hello world","expected":"1"},
        {"input":"a b c d","expected":"3"},
        {"input":"nospaces","expected":"0"},
        {"input":" ","expected":"1"},
        {"input":"  ","expected":"2"},
        {"input":"one two three","expected":"2"},
        {"input":"a","expected":"0"},
        {"input":"hello  world","expected":"2"},
        {"input":"test case here","expected":"2"},
        {"input":"   three   ","expected":"6"},
        {"input":"hi there","expected":"1"},
        {"input":"abc","expected":"0"},
        {"input":"x y","expected":"1"},
        {"input":"a b c d e","expected":"4"},
        {"input":"single","expected":"0"},
    ],
    "Remove Character From String": [
        {"input":"hello\\nl","expected":"heo"},
        {"input":"world\\no","expected":"wrld"},
        {"input":"abc\\nb","expected":"ac"},
        {"input":"test\\nt","expected":"es"},
        {"input":"aaa\\na","expected":""},
        {"input":"python\\np","expected":"ython"},
        {"input":"hello\\nx","expected":"hello"},
        {"input":"abcabc\\nc","expected":"abab"},
        {"input":"programming\\ng","expected":"prorammin"},
        {"input":"remove\\ne","expected":"rmov"},
        {"input":"data\\na","expected":"dt"},
        {"input":"coding\\nd","expected":"coing"},
        {"input":"xyz\\nz","expected":"xy"},
        {"input":"aeiou\\na","expected":"eiou"},
        {"input":"mississippi\\ni","expected":"msssspp"},
    ],
    "Replace Character": [
        {"input":"hello\\nl\\nx","expected":"hexxo"},
        {"input":"world\\no\\na","expected":"warld"},
        {"input":"abc\\nb\\nz","expected":"azc"},
        {"input":"test\\nt\\nm","expected":"mesm"},
        {"input":"aaa\\na\\nb","expected":"bbb"},
        {"input":"python\\np\\nP","expected":"Python"},
        {"input":"hello\\nx\\ny","expected":"hello"},
        {"input":"abcabc\\nc\\nz","expected":"abzabz"},
        {"input":"data\\na\\no","expected":"doto"},
        {"input":"code\\ne\\na","expected":"coda"},
        {"input":"xyz\\nx\\na","expected":"ayz"},
        {"input":"aba\\na\\nc","expected":"cbc"},
        {"input":"test\\ne\\na","expected":"tast"},
        {"input":"noon\\nn\\nm","expected":"moom"},
        {"input":"deed\\nd\\nb","expected":"beeb"},
    ],
}

def generate_sql():
    lines = []
    lines.append("-- ============================================")
    lines.append("-- AUTO-GENERATED: 15 test cases per problem")
    lines.append("-- First 3 = sample (visible), remaining 12 = hidden")
    lines.append("-- ============================================")
    lines.append("")

    for title, cases in PROBLEMS.items():
        assert len(cases) == 15, f"{title} has {len(cases)} cases, need 15"
        # Mark first 3 as sample
        tc_list = []
        for i, c in enumerate(cases):
            tc = dict(c)
            tc["sample"] = (i < 3)
            tc_list.append(tc)

        tc_json = json.dumps(tc_list, separators=(',', ':'))
        # Escape single quotes for SQL
        tc_sql = tc_json.replace("'", "''")

        lines.append(f"UPDATE problems SET test_cases = '{tc_sql}' WHERE title = '{title}';")
        lines.append("")

    return "\n".join(lines)

if __name__ == "__main__":
    sql = generate_sql()
    out_path = "/home/gowtham/codeclash/scripts/update_testcases.sql"
    with open(out_path, "w") as f:
        f.write(sql)
    print(f"Generated {len(PROBLEMS)} problem updates to {out_path}")
