-- ============================================
-- AUTO-GENERATED: 15 test cases per problem
-- First 3 = sample (visible), remaining 12 = hidden
-- ============================================

UPDATE problems SET test_cases = '[{"input":"[2,7,11,15]\\n9","expected":"[0, 1]","sample":true},{"input":"[3,2,4]\\n6","expected":"[1, 2]","sample":true},{"input":"[3,3]\\n6","expected":"[0, 1]","sample":true},{"input":"[1,5,3,7]\\n8","expected":"[1, 3]","sample":false},{"input":"[4,6,1]\\n5","expected":"[0, 2]","sample":false},{"input":"[0,4,3,0]\\n0","expected":"[0, 3]","sample":false},{"input":"[2,2]\\n4","expected":"[0, 1]","sample":false},{"input":"[1,2,3,4,5]\\n9","expected":"[3, 4]","sample":false},{"input":"[10,20,30]\\n50","expected":"[1, 2]","sample":false},{"input":"[-1,0,1]\\n0","expected":"[0, 2]","sample":false},{"input":"[100,200]\\n300","expected":"[0, 1]","sample":false},{"input":"[5,10,15,20]\\n25","expected":"[1, 2]","sample":false},{"input":"[1,3,5,7,9]\\n10","expected":"[0, 4]","sample":false},{"input":"[6,6]\\n12","expected":"[0, 1]","sample":false},{"input":"[1,4,5,6]\\n10","expected":"[1, 3]","sample":false}]' WHERE title = 'Two Sum';

UPDATE problems SET test_cases = '[{"input":"hello","expected":"olleh","sample":true},{"input":"world","expected":"dlrow","sample":true},{"input":"abcd","expected":"dcba","sample":true},{"input":"a","expected":"a","sample":false},{"input":"ab","expected":"ba","sample":false},{"input":"racecar","expected":"racecar","sample":false},{"input":"python","expected":"nohtyp","sample":false},{"input":"12345","expected":"54321","sample":false},{"input":"OpenAI","expected":"IAnepO","sample":false},{"input":"abcdef","expected":"fedcba","sample":false},{"input":"zzz","expected":"zzz","sample":false},{"input":"code","expected":"edoc","sample":false},{"input":"test","expected":"tset","sample":false},{"input":"hello world","expected":"dlrow olleh","sample":false},{"input":"madam","expected":"madam","sample":false}]' WHERE title = 'Reverse String';

UPDATE problems SET test_cases = '[{"input":"5","expected":"1\\n2\\nFizz\\n4\\nBuzz","sample":true},{"input":"15","expected":"1\\n2\\nFizz\\n4\\nBuzz\\nFizz\\n7\\n8\\nFizz\\nBuzz\\n11\\nFizz\\n13\\n14\\nFizzBuzz","sample":true},{"input":"3","expected":"1\\n2\\nFizz","sample":true},{"input":"1","expected":"1","sample":false},{"input":"2","expected":"1\\n2","sample":false},{"input":"6","expected":"1\\n2\\nFizz\\n4\\nBuzz\\nFizz","sample":false},{"input":"10","expected":"1\\n2\\nFizz\\n4\\nBuzz\\nFizz\\n7\\n8\\nFizz\\nBuzz","sample":false},{"input":"4","expected":"1\\n2\\nFizz\\n4","sample":false},{"input":"7","expected":"1\\n2\\nFizz\\n4\\nBuzz\\nFizz\\n7","sample":false},{"input":"9","expected":"1\\n2\\nFizz\\n4\\nBuzz\\nFizz\\n7\\n8\\nFizz","sample":false},{"input":"11","expected":"1\\n2\\nFizz\\n4\\nBuzz\\nFizz\\n7\\n8\\nFizz\\nBuzz\\n11","sample":false},{"input":"12","expected":"1\\n2\\nFizz\\n4\\nBuzz\\nFizz\\n7\\n8\\nFizz\\nBuzz\\n11\\nFizz","sample":false},{"input":"13","expected":"1\\n2\\nFizz\\n4\\nBuzz\\nFizz\\n7\\n8\\nFizz\\nBuzz\\n11\\nFizz\\n13","sample":false},{"input":"14","expected":"1\\n2\\nFizz\\n4\\nBuzz\\nFizz\\n7\\n8\\nFizz\\nBuzz\\n11\\nFizz\\n13\\n14","sample":false},{"input":"8","expected":"1\\n2\\nFizz\\n4\\nBuzz\\nFizz\\n7\\n8","sample":false}]' WHERE title = 'FizzBuzz';

UPDATE problems SET test_cases = '[{"input":"()[]{}","expected":"True","sample":true},{"input":"(]","expected":"False","sample":true},{"input":"([)]","expected":"False","sample":true},{"input":"()","expected":"True","sample":false},{"input":"{}","expected":"True","sample":false},{"input":"[]","expected":"True","sample":false},{"input":"((()))","expected":"True","sample":false},{"input":"(","expected":"False","sample":false},{"input":")","expected":"False","sample":false},{"input":"({[]})","expected":"True","sample":false},{"input":"[{()}]","expected":"True","sample":false},{"input":"","expected":"True","sample":false},{"input":"(()","expected":"False","sample":false},{"input":"({})[()]","expected":"True","sample":false},{"input":"([{}])()","expected":"True","sample":false}]' WHERE title = 'Valid Parentheses';

UPDATE problems SET test_cases = '[{"input":"[1,3,5]\\n[2,4,6]","expected":"[1, 2, 3, 4, 5, 6]","sample":true},{"input":"[1,2]\\n[3,4]","expected":"[1, 2, 3, 4]","sample":true},{"input":"[1]\\n[2]","expected":"[1, 2]","sample":true},{"input":"[]\\n[1,2,3]","expected":"[1, 2, 3]","sample":false},{"input":"[1,2,3]\\n[]","expected":"[1, 2, 3]","sample":false},{"input":"[1,1,1]\\n[1,1,1]","expected":"[1, 1, 1, 1, 1, 1]","sample":false},{"input":"[5,10,15]\\n[3,7,12]","expected":"[3, 5, 7, 10, 12, 15]","sample":false},{"input":"[1,3,5,7]\\n[2,4,6,8]","expected":"[1, 2, 3, 4, 5, 6, 7, 8]","sample":false},{"input":"[100]\\n[1]","expected":"[1, 100]","sample":false},{"input":"[2,4]\\n[1,3,5]","expected":"[1, 2, 3, 4, 5]","sample":false},{"input":"[0,0]\\n[0,0]","expected":"[0, 0, 0, 0]","sample":false},{"input":"[10,20,30]\\n[5,15,25]","expected":"[5, 10, 15, 20, 25, 30]","sample":false},{"input":"[-3,-1]\\n[-2,0]","expected":"[-3, -2, -1, 0]","sample":false},{"input":"[1,2,3,4,5]\\n[6,7,8,9,10]","expected":"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]","sample":false},{"input":"[50]\\n[25,75]","expected":"[25, 50, 75]","sample":false}]' WHERE title = 'Merge Sorted Arrays';

UPDATE problems SET test_cases = '[{"input":"[1,3,5,7,9]\\n5","expected":"2","sample":true},{"input":"[1,3,5,7,9]\\n2","expected":"-1","sample":true},{"input":"[1,2,3,4,5]\\n1","expected":"0","sample":true},{"input":"[1,2,3,4,5]\\n5","expected":"4","sample":false},{"input":"[10,20,30,40,50]\\n30","expected":"2","sample":false},{"input":"[1]\\n1","expected":"0","sample":false},{"input":"[1]\\n2","expected":"-1","sample":false},{"input":"[2,4,6,8,10]\\n8","expected":"3","sample":false},{"input":"[1,3,5,7,9,11]\\n11","expected":"5","sample":false},{"input":"[100,200,300]\\n100","expected":"0","sample":false},{"input":"[5,15,25,35,45]\\n45","expected":"4","sample":false},{"input":"[1,2,3]\\n4","expected":"-1","sample":false},{"input":"[10,20,30,40]\\n10","expected":"0","sample":false},{"input":"[3,6,9,12,15]\\n9","expected":"2","sample":false},{"input":"[1,5,10,15,20,25]\\n15","expected":"3","sample":false}]' WHERE title = 'Binary Search';

UPDATE problems SET test_cases = '[{"input":"abcde\\nace","expected":"3","sample":true},{"input":"abc\\nabc","expected":"3","sample":true},{"input":"abc\\ndef","expected":"0","sample":true},{"input":"abcd\\nabd","expected":"3","sample":false},{"input":"a\\na","expected":"1","sample":false},{"input":"a\\nb","expected":"0","sample":false},{"input":"abcdef\\nacf","expected":"3","sample":false},{"input":"xyz\\nxyz","expected":"3","sample":false},{"input":"abcde\\nbce","expected":"3","sample":false},{"input":"abc\\n","expected":"0","sample":false},{"input":"pqrs\\nprt","expected":"2","sample":false},{"input":"aab\\nazb","expected":"2","sample":false},{"input":"bl\\nyby","expected":"1","sample":false},{"input":"abcba\\nabcbcba","expected":"5","sample":false},{"input":"oxcpqrsvwf\\nshmtulqrypy","expected":"2","sample":false}]' WHERE title = 'Longest Common Subsequence';

UPDATE problems SET test_cases = '[{"input":"[1,3]\\n[2]","expected":"2.0","sample":true},{"input":"[1,2]\\n[3,4]","expected":"2.5","sample":true},{"input":"[0,0]\\n[0,0]","expected":"0.0","sample":true},{"input":"[1]\\n[2,3]","expected":"2.0","sample":false},{"input":"[1,2,3]\\n[4,5,6]","expected":"3.5","sample":false},{"input":"[1]\\n[1]","expected":"1.0","sample":false},{"input":"[2]\\n[1,3,4]","expected":"2.5","sample":false},{"input":"[1,3,5]\\n[2,4,6]","expected":"3.5","sample":false},{"input":"[1,2]\\n[1,2]","expected":"1.5","sample":false},{"input":"[3]\\n[1,2]","expected":"2.0","sample":false},{"input":"[1,5,9]\\n[2,6,10]","expected":"5.5","sample":false},{"input":"[100]\\n[200]","expected":"150.0","sample":false},{"input":"[1,2,3,4]\\n[5,6,7,8]","expected":"4.5","sample":false},{"input":"[10,20]\\n[15,25]","expected":"17.5","sample":false},{"input":"[1]\\n[2,3,4,5]","expected":"3.0","sample":false}]' WHERE title = 'Median of Two Sorted Arrays';

UPDATE problems SET test_cases = '[{"input":"[1,5,3,9,2]","expected":"9","sample":true},{"input":"[10,20,5]","expected":"20","sample":true},{"input":"[1]","expected":"1","sample":true},{"input":"[3,3,3]","expected":"3","sample":false},{"input":"[-1,-5,-3]","expected":"-1","sample":false},{"input":"[100,200,300]","expected":"300","sample":false},{"input":"[0,0,0,0]","expected":"0","sample":false},{"input":"[7]","expected":"7","sample":false},{"input":"[5,4,3,2,1]","expected":"5","sample":false},{"input":"[1,2,3,4,5]","expected":"5","sample":false},{"input":"[-10,0,10]","expected":"10","sample":false},{"input":"[999,1000,998]","expected":"1000","sample":false},{"input":"[42,17,88,3]","expected":"88","sample":false},{"input":"[50,50]","expected":"50","sample":false},{"input":"[1,100,1]","expected":"100","sample":false}]' WHERE title = 'Find Maximum Number';

UPDATE problems SET test_cases = '[{"input":"[1,2,3,4]","expected":"10","sample":true},{"input":"[5,5,5]","expected":"15","sample":true},{"input":"[0]","expected":"0","sample":true},{"input":"[10,20,30]","expected":"60","sample":false},{"input":"[1]","expected":"1","sample":false},{"input":"[-1,1]","expected":"0","sample":false},{"input":"[100,200,300]","expected":"600","sample":false},{"input":"[7,3]","expected":"10","sample":false},{"input":"[0,0,0]","expected":"0","sample":false},{"input":"[1,2,3,4,5]","expected":"15","sample":false},{"input":"[10]","expected":"10","sample":false},{"input":"[50,50,50,50]","expected":"200","sample":false},{"input":"[-5,-3,-2]","expected":"-10","sample":false},{"input":"[99,1]","expected":"100","sample":false},{"input":"[1,1,1,1,1,1,1,1,1,1]","expected":"10","sample":false}]' WHERE title = 'Sum of Array';

UPDATE problems SET test_cases = '[{"input":"7","expected":"Odd","sample":true},{"input":"4","expected":"Even","sample":true},{"input":"0","expected":"Even","sample":true},{"input":"1","expected":"Odd","sample":false},{"input":"2","expected":"Even","sample":false},{"input":"100","expected":"Even","sample":false},{"input":"99","expected":"Odd","sample":false},{"input":"13","expected":"Odd","sample":false},{"input":"50","expected":"Even","sample":false},{"input":"1001","expected":"Odd","sample":false},{"input":"256","expected":"Even","sample":false},{"input":"3","expected":"Odd","sample":false},{"input":"10","expected":"Even","sample":false},{"input":"555","expected":"Odd","sample":false},{"input":"1024","expected":"Even","sample":false}]' WHERE title = 'Check Even or Odd';

UPDATE problems SET test_cases = '[{"input":"hello","expected":"2","sample":true},{"input":"aeiou","expected":"5","sample":true},{"input":"bcdfg","expected":"0","sample":true},{"input":"a","expected":"1","sample":false},{"input":"xyz","expected":"0","sample":false},{"input":"programming","expected":"3","sample":false},{"input":"AEIOU","expected":"5","sample":false},{"input":"python","expected":"1","sample":false},{"input":"beautiful","expected":"5","sample":false},{"input":"rhythm","expected":"0","sample":false},{"input":"education","expected":"5","sample":false},{"input":"b","expected":"0","sample":false},{"input":"umbrella","expected":"3","sample":false},{"input":"queue","expected":"4","sample":false},{"input":"strength","expected":"1","sample":false}]' WHERE title = 'Count Vowels';

UPDATE problems SET test_cases = '[{"input":"madam","expected":"True","sample":true},{"input":"hello","expected":"False","sample":true},{"input":"a","expected":"True","sample":true},{"input":"racecar","expected":"True","sample":false},{"input":"ab","expected":"False","sample":false},{"input":"aba","expected":"True","sample":false},{"input":"abba","expected":"True","sample":false},{"input":"abc","expected":"False","sample":false},{"input":"level","expected":"True","sample":false},{"input":"noon","expected":"True","sample":false},{"input":"kayak","expected":"True","sample":false},{"input":"world","expected":"False","sample":false},{"input":"deed","expected":"True","sample":false},{"input":"python","expected":"False","sample":false},{"input":"civic","expected":"True","sample":false}]' WHERE title = 'Palindrome String';

UPDATE problems SET test_cases = '[{"input":"[4,2,7,1]","expected":"1","sample":true},{"input":"[10,5,15]","expected":"5","sample":true},{"input":"[5]","expected":"5","sample":true},{"input":"[3,3,3]","expected":"3","sample":false},{"input":"[-1,-5,-3]","expected":"-5","sample":false},{"input":"[100,200,300]","expected":"100","sample":false},{"input":"[0,0,0,0]","expected":"0","sample":false},{"input":"[9,8,7,6,5]","expected":"5","sample":false},{"input":"[1,2,3]","expected":"1","sample":false},{"input":"[-10,0,10]","expected":"-10","sample":false},{"input":"[50]","expected":"50","sample":false},{"input":"[999,1,1000]","expected":"1","sample":false},{"input":"[42,17,88,3]","expected":"3","sample":false},{"input":"[50,50]","expected":"50","sample":false},{"input":"[7,2,9,4]","expected":"2","sample":false}]' WHERE title = 'Find Minimum';

UPDATE problems SET test_cases = '[{"input":"5","expected":"120","sample":true},{"input":"0","expected":"1","sample":true},{"input":"3","expected":"6","sample":true},{"input":"1","expected":"1","sample":false},{"input":"2","expected":"2","sample":false},{"input":"4","expected":"24","sample":false},{"input":"6","expected":"720","sample":false},{"input":"7","expected":"5040","sample":false},{"input":"8","expected":"40320","sample":false},{"input":"9","expected":"362880","sample":false},{"input":"10","expected":"3628800","sample":false},{"input":"11","expected":"39916800","sample":false},{"input":"12","expected":"479001600","sample":false},{"input":"13","expected":"6227020800","sample":false},{"input":"14","expected":"87178291200","sample":false}]' WHERE title = 'Factorial';

UPDATE problems SET test_cases = '[{"input":"6","expected":"8","sample":true},{"input":"1","expected":"1","sample":true},{"input":"5","expected":"5","sample":true},{"input":"0","expected":"0","sample":false},{"input":"2","expected":"1","sample":false},{"input":"3","expected":"2","sample":false},{"input":"4","expected":"3","sample":false},{"input":"7","expected":"13","sample":false},{"input":"8","expected":"21","sample":false},{"input":"9","expected":"34","sample":false},{"input":"10","expected":"55","sample":false},{"input":"11","expected":"89","sample":false},{"input":"12","expected":"144","sample":false},{"input":"13","expected":"233","sample":false},{"input":"14","expected":"377","sample":false}]' WHERE title = 'Fibonacci Nth';

UPDATE problems SET test_cases = '[{"input":"[1,2,3]","expected":"[3, 2, 1]","sample":true},{"input":"[10,20]","expected":"[20, 10]","sample":true},{"input":"[5]","expected":"[5]","sample":true},{"input":"[1,2,3,4,5]","expected":"[5, 4, 3, 2, 1]","sample":false},{"input":"[0,0,0]","expected":"[0, 0, 0]","sample":false},{"input":"[9,8,7,6]","expected":"[6, 7, 8, 9]","sample":false},{"input":"[100]","expected":"[100]","sample":false},{"input":"[-1,-2,-3]","expected":"[-3, -2, -1]","sample":false},{"input":"[1,1,1,1]","expected":"[1, 1, 1, 1]","sample":false},{"input":"[3,6,9]","expected":"[9, 6, 3]","sample":false},{"input":"[2,4]","expected":"[4, 2]","sample":false},{"input":"[7,14,21,28]","expected":"[28, 21, 14, 7]","sample":false},{"input":"[50,40,30,20,10]","expected":"[10, 20, 30, 40, 50]","sample":false},{"input":"[1,3,5,7,9]","expected":"[9, 7, 5, 3, 1]","sample":false},{"input":"[11,22,33]","expected":"[33, 22, 11]","sample":false}]' WHERE title = 'Reverse Array';

UPDATE problems SET test_cases = '[{"input":"12345","expected":"5","sample":true},{"input":"100","expected":"3","sample":true},{"input":"9","expected":"1","sample":true},{"input":"0","expected":"1","sample":false},{"input":"10","expected":"2","sample":false},{"input":"99999","expected":"5","sample":false},{"input":"1000000","expected":"7","sample":false},{"input":"42","expected":"2","sample":false},{"input":"7","expected":"1","sample":false},{"input":"555","expected":"3","sample":false},{"input":"1234567890","expected":"10","sample":false},{"input":"11","expected":"2","sample":false},{"input":"123","expected":"3","sample":false},{"input":"9999","expected":"4","sample":false},{"input":"50","expected":"2","sample":false}]' WHERE title = 'Count Digits';

UPDATE problems SET test_cases = '[{"input":"123","expected":"6","sample":true},{"input":"100","expected":"1","sample":true},{"input":"555","expected":"15","sample":true},{"input":"0","expected":"0","sample":false},{"input":"9","expected":"9","sample":false},{"input":"99","expected":"18","sample":false},{"input":"12","expected":"3","sample":false},{"input":"999","expected":"27","sample":false},{"input":"1001","expected":"2","sample":false},{"input":"45","expected":"9","sample":false},{"input":"111","expected":"3","sample":false},{"input":"246","expected":"12","sample":false},{"input":"789","expected":"24","sample":false},{"input":"50","expected":"5","sample":false},{"input":"321","expected":"6","sample":false}]' WHERE title = 'Sum of Digits';

UPDATE problems SET test_cases = '[{"input":"7","expected":"True","sample":true},{"input":"4","expected":"False","sample":true},{"input":"2","expected":"True","sample":true},{"input":"1","expected":"False","sample":false},{"input":"3","expected":"True","sample":false},{"input":"9","expected":"False","sample":false},{"input":"11","expected":"True","sample":false},{"input":"13","expected":"True","sample":false},{"input":"15","expected":"False","sample":false},{"input":"17","expected":"True","sample":false},{"input":"19","expected":"True","sample":false},{"input":"20","expected":"False","sample":false},{"input":"23","expected":"True","sample":false},{"input":"25","expected":"False","sample":false},{"input":"29","expected":"True","sample":false}]' WHERE title = 'Check Prime';

UPDATE problems SET test_cases = '[{"input":"3 7 5","expected":"7","sample":true},{"input":"10 5 15","expected":"15","sample":true},{"input":"1 1 1","expected":"1","sample":true},{"input":"0 0 0","expected":"0","sample":false},{"input":"100 200 300","expected":"300","sample":false},{"input":"-1 -2 -3","expected":"-1","sample":false},{"input":"5 5 3","expected":"5","sample":false},{"input":"10 10 10","expected":"10","sample":false},{"input":"99 100 98","expected":"100","sample":false},{"input":"1 2 3","expected":"3","sample":false},{"input":"50 25 75","expected":"75","sample":false},{"input":"7 3 9","expected":"9","sample":false},{"input":"1000 999 998","expected":"1000","sample":false},{"input":"0 1 -1","expected":"1","sample":false},{"input":"42 42 41","expected":"42","sample":false}]' WHERE title = 'Largest of Three';

UPDATE problems SET test_cases = '[{"input":"hello","expected":"5","sample":true},{"input":"world","expected":"5","sample":true},{"input":"a","expected":"1","sample":true},{"input":"","expected":"0","sample":false},{"input":"ab","expected":"2","sample":false},{"input":"python","expected":"6","sample":false},{"input":"programming","expected":"11","sample":false},{"input":"test","expected":"4","sample":false},{"input":"hi","expected":"2","sample":false},{"input":"abcdef","expected":"6","sample":false},{"input":"123","expected":"3","sample":false},{"input":"x","expected":"1","sample":false},{"input":"longer string","expected":"13","sample":false},{"input":"code","expected":"4","sample":false},{"input":"abcdefghij","expected":"10","sample":false}]' WHERE title = 'String Length';

UPDATE problems SET test_cases = '[{"input":"hello","expected":"HELLO","sample":true},{"input":"World","expected":"WORLD","sample":true},{"input":"abc","expected":"ABC","sample":true},{"input":"a","expected":"A","sample":false},{"input":"python","expected":"PYTHON","sample":false},{"input":"test","expected":"TEST","sample":false},{"input":"HeLLo","expected":"HELLO","sample":false},{"input":"xyz","expected":"XYZ","sample":false},{"input":"code","expected":"CODE","sample":false},{"input":"java","expected":"JAVA","sample":false},{"input":"hi","expected":"HI","sample":false},{"input":"ALREADY","expected":"ALREADY","sample":false},{"input":"open","expected":"OPEN","sample":false},{"input":"data","expected":"DATA","sample":false},{"input":"fun","expected":"FUN","sample":false}]' WHERE title = 'Uppercase String';

UPDATE problems SET test_cases = '[{"input":"HELLO","expected":"hello","sample":true},{"input":"World","expected":"world","sample":true},{"input":"ABC","expected":"abc","sample":true},{"input":"A","expected":"a","sample":false},{"input":"PYTHON","expected":"python","sample":false},{"input":"TEST","expected":"test","sample":false},{"input":"HeLLo","expected":"hello","sample":false},{"input":"XYZ","expected":"xyz","sample":false},{"input":"CODE","expected":"code","sample":false},{"input":"JAVA","expected":"java","sample":false},{"input":"HI","expected":"hi","sample":false},{"input":"already","expected":"already","sample":false},{"input":"OPEN","expected":"open","sample":false},{"input":"DATA","expected":"data","sample":false},{"input":"FUN","expected":"fun","sample":false}]' WHERE title = 'Lowercase String';

UPDATE problems SET test_cases = '[{"input":"5","expected":"25","sample":true},{"input":"0","expected":"0","sample":true},{"input":"3","expected":"9","sample":true},{"input":"1","expected":"1","sample":false},{"input":"10","expected":"100","sample":false},{"input":"7","expected":"49","sample":false},{"input":"12","expected":"144","sample":false},{"input":"2","expected":"4","sample":false},{"input":"4","expected":"16","sample":false},{"input":"6","expected":"36","sample":false},{"input":"8","expected":"64","sample":false},{"input":"9","expected":"81","sample":false},{"input":"11","expected":"121","sample":false},{"input":"15","expected":"225","sample":false},{"input":"20","expected":"400","sample":false}]' WHERE title = 'Square of Numbers';

UPDATE problems SET test_cases = '[{"input":"3","expected":"27","sample":true},{"input":"0","expected":"0","sample":true},{"input":"2","expected":"8","sample":true},{"input":"1","expected":"1","sample":false},{"input":"5","expected":"125","sample":false},{"input":"4","expected":"64","sample":false},{"input":"6","expected":"216","sample":false},{"input":"7","expected":"343","sample":false},{"input":"10","expected":"1000","sample":false},{"input":"8","expected":"512","sample":false},{"input":"9","expected":"729","sample":false},{"input":"11","expected":"1331","sample":false},{"input":"12","expected":"1728","sample":false},{"input":"15","expected":"3375","sample":false},{"input":"20","expected":"8000","sample":false}]' WHERE title = 'Cube of Numbers';

UPDATE problems SET test_cases = '[{"input":"3 5","expected":"5 3","sample":true},{"input":"10 20","expected":"20 10","sample":true},{"input":"0 0","expected":"0 0","sample":true},{"input":"1 2","expected":"2 1","sample":false},{"input":"-1 1","expected":"1 -1","sample":false},{"input":"100 200","expected":"200 100","sample":false},{"input":"7 3","expected":"3 7","sample":false},{"input":"50 50","expected":"50 50","sample":false},{"input":"99 1","expected":"1 99","sample":false},{"input":"5 10","expected":"10 5","sample":false},{"input":"42 24","expected":"24 42","sample":false},{"input":"0 1","expected":"1 0","sample":false},{"input":"1000 2000","expected":"2000 1000","sample":false},{"input":"13 31","expected":"31 13","sample":false},{"input":"8 4","expected":"4 8","sample":false}]' WHERE title = 'Swap Two Numbers';

UPDATE problems SET test_cases = '[{"input":"2000","expected":"True","sample":true},{"input":"1900","expected":"False","sample":true},{"input":"2024","expected":"True","sample":true},{"input":"2023","expected":"False","sample":false},{"input":"2100","expected":"False","sample":false},{"input":"1600","expected":"True","sample":false},{"input":"2004","expected":"True","sample":false},{"input":"1999","expected":"False","sample":false},{"input":"2020","expected":"True","sample":false},{"input":"1800","expected":"False","sample":false},{"input":"400","expected":"True","sample":false},{"input":"100","expected":"False","sample":false},{"input":"2016","expected":"True","sample":false},{"input":"2019","expected":"False","sample":false},{"input":"2400","expected":"True","sample":false}]' WHERE title = 'Is Leap Year Check';

UPDATE problems SET test_cases = '[{"input":"5","expected":"15","sample":true},{"input":"10","expected":"55","sample":true},{"input":"1","expected":"1","sample":true},{"input":"0","expected":"0","sample":false},{"input":"3","expected":"6","sample":false},{"input":"100","expected":"5050","sample":false},{"input":"7","expected":"28","sample":false},{"input":"20","expected":"210","sample":false},{"input":"50","expected":"1275","sample":false},{"input":"2","expected":"3","sample":false},{"input":"4","expected":"10","sample":false},{"input":"15","expected":"120","sample":false},{"input":"25","expected":"325","sample":false},{"input":"6","expected":"21","sample":false},{"input":"8","expected":"36","sample":false}]' WHERE title = 'Sum of First N Numbers';

UPDATE problems SET test_cases = '[{"input":"2 3","expected":"8","sample":true},{"input":"5 2","expected":"25","sample":true},{"input":"10 0","expected":"1","sample":true},{"input":"3 3","expected":"27","sample":false},{"input":"2 10","expected":"1024","sample":false},{"input":"1 100","expected":"1","sample":false},{"input":"7 2","expected":"49","sample":false},{"input":"4 3","expected":"64","sample":false},{"input":"2 0","expected":"1","sample":false},{"input":"5 3","expected":"125","sample":false},{"input":"6 2","expected":"36","sample":false},{"input":"3 4","expected":"81","sample":false},{"input":"2 5","expected":"32","sample":false},{"input":"9 2","expected":"81","sample":false},{"input":"10 3","expected":"1000","sample":false}]' WHERE title = 'Power of Number';

UPDATE problems SET test_cases = '[{"input":"123","expected":"321","sample":true},{"input":"100","expected":"1","sample":true},{"input":"5","expected":"5","sample":true},{"input":"1234","expected":"4321","sample":false},{"input":"0","expected":"0","sample":false},{"input":"10","expected":"1","sample":false},{"input":"999","expected":"999","sample":false},{"input":"1001","expected":"1001","sample":false},{"input":"50","expected":"5","sample":false},{"input":"12","expected":"21","sample":false},{"input":"54321","expected":"12345","sample":false},{"input":"7","expected":"7","sample":false},{"input":"200","expected":"2","sample":false},{"input":"9876","expected":"6789","sample":false},{"input":"1010","expected":"101","sample":false}]' WHERE title = 'Reverse Number';

UPDATE problems SET test_cases = '[{"input":"153","expected":"True","sample":true},{"input":"370","expected":"True","sample":true},{"input":"100","expected":"False","sample":true},{"input":"1","expected":"True","sample":false},{"input":"0","expected":"True","sample":false},{"input":"371","expected":"True","sample":false},{"input":"407","expected":"True","sample":false},{"input":"10","expected":"False","sample":false},{"input":"9","expected":"True","sample":false},{"input":"123","expected":"False","sample":false},{"input":"5","expected":"True","sample":false},{"input":"200","expected":"False","sample":false},{"input":"8","expected":"True","sample":false},{"input":"999","expected":"False","sample":false},{"input":"2","expected":"True","sample":false}]' WHERE title = 'Check Armstrong Number';

UPDATE problems SET test_cases = '[{"input":"12 8","expected":"4","sample":true},{"input":"100 75","expected":"25","sample":true},{"input":"7 3","expected":"1","sample":true},{"input":"6 6","expected":"6","sample":false},{"input":"10 5","expected":"5","sample":false},{"input":"1 1","expected":"1","sample":false},{"input":"24 36","expected":"12","sample":false},{"input":"15 10","expected":"5","sample":false},{"input":"21 14","expected":"7","sample":false},{"input":"48 18","expected":"6","sample":false},{"input":"100 10","expected":"10","sample":false},{"input":"9 6","expected":"3","sample":false},{"input":"17 13","expected":"1","sample":false},{"input":"56 98","expected":"14","sample":false},{"input":"81 27","expected":"27","sample":false}]' WHERE title = 'GCD of Two Numbers';

UPDATE problems SET test_cases = '[{"input":"4 6","expected":"12","sample":true},{"input":"3 5","expected":"15","sample":true},{"input":"7 3","expected":"21","sample":true},{"input":"1 1","expected":"1","sample":false},{"input":"6 6","expected":"6","sample":false},{"input":"2 3","expected":"6","sample":false},{"input":"12 8","expected":"24","sample":false},{"input":"10 15","expected":"30","sample":false},{"input":"5 7","expected":"35","sample":false},{"input":"4 10","expected":"20","sample":false},{"input":"9 6","expected":"18","sample":false},{"input":"8 12","expected":"24","sample":false},{"input":"15 20","expected":"60","sample":false},{"input":"3 9","expected":"9","sample":false},{"input":"14 21","expected":"42","sample":false}]' WHERE title = 'LCM of Two Numbers';

UPDATE problems SET test_cases = '[{"input":"5","expected":"5 10 15 20 25 30 35 40 45 50","sample":true},{"input":"3","expected":"3 6 9 12 15 18 21 24 27 30","sample":true},{"input":"1","expected":"1 2 3 4 5 6 7 8 9 10","sample":true},{"input":"2","expected":"2 4 6 8 10 12 14 16 18 20","sample":false},{"input":"7","expected":"7 14 21 28 35 42 49 56 63 70","sample":false},{"input":"10","expected":"10 20 30 40 50 60 70 80 90 100","sample":false},{"input":"4","expected":"4 8 12 16 20 24 28 32 36 40","sample":false},{"input":"6","expected":"6 12 18 24 30 36 42 48 54 60","sample":false},{"input":"8","expected":"8 16 24 32 40 48 56 64 72 80","sample":false},{"input":"9","expected":"9 18 27 36 45 54 63 72 81 90","sample":false},{"input":"11","expected":"11 22 33 44 55 66 77 88 99 110","sample":false},{"input":"12","expected":"12 24 36 48 60 72 84 96 108 120","sample":false},{"input":"15","expected":"15 30 45 60 75 90 105 120 135 150","sample":false},{"input":"20","expected":"20 40 60 80 100 120 140 160 180 200","sample":false},{"input":"13","expected":"13 26 39 52 65 78 91 104 117 130","sample":false}]' WHERE title = 'Multiplication Table';

UPDATE problems SET test_cases = '[{"input":"[1,2,3,4,5,6]","expected":"12","sample":true},{"input":"[2,4,6]","expected":"12","sample":true},{"input":"[1,3,5]","expected":"0","sample":true},{"input":"[10,20,30]","expected":"60","sample":false},{"input":"[0]","expected":"0","sample":false},{"input":"[1]","expected":"0","sample":false},{"input":"[2]","expected":"2","sample":false},{"input":"[1,2,3,4]","expected":"6","sample":false},{"input":"[100,200]","expected":"300","sample":false},{"input":"[7,8,9,10]","expected":"18","sample":false},{"input":"[0,0,0]","expected":"0","sample":false},{"input":"[11,22,33,44]","expected":"66","sample":false},{"input":"[5,10,15,20]","expected":"30","sample":false},{"input":"[1,2]","expected":"2","sample":false},{"input":"[4,4,4]","expected":"12","sample":false}]' WHERE title = 'Sum of Even Numbers';

UPDATE problems SET test_cases = '[{"input":"[1,2,3,4,5]","expected":"9","sample":true},{"input":"[1,3,5]","expected":"9","sample":true},{"input":"[2,4,6]","expected":"0","sample":true},{"input":"[10,11,12,13]","expected":"24","sample":false},{"input":"[0]","expected":"0","sample":false},{"input":"[1]","expected":"1","sample":false},{"input":"[3]","expected":"3","sample":false},{"input":"[1,2,3,4]","expected":"4","sample":false},{"input":"[99,100]","expected":"99","sample":false},{"input":"[7,8,9,10]","expected":"16","sample":false},{"input":"[0,0,0]","expected":"0","sample":false},{"input":"[11,22,33,44]","expected":"44","sample":false},{"input":"[5,10,15,20]","expected":"20","sample":false},{"input":"[1,2]","expected":"1","sample":false},{"input":"[3,5,7]","expected":"15","sample":false}]' WHERE title = 'Sum of Odd Numbers';

UPDATE problems SET test_cases = '[{"input":"[1,2,3,4,5,6]","expected":"3","sample":true},{"input":"[2,4,6,8]","expected":"4","sample":true},{"input":"[1,3,5]","expected":"0","sample":true},{"input":"[10]","expected":"1","sample":false},{"input":"[1]","expected":"0","sample":false},{"input":"[0]","expected":"1","sample":false},{"input":"[2,3,4,5]","expected":"2","sample":false},{"input":"[100,200,300]","expected":"3","sample":false},{"input":"[7,8,9,10]","expected":"2","sample":false},{"input":"[1,2,3,4,5,6,7,8]","expected":"4","sample":false},{"input":"[11,22,33,44,55]","expected":"2","sample":false},{"input":"[0,0,0]","expected":"3","sample":false},{"input":"[1,1,1]","expected":"0","sample":false},{"input":"[2,2,2]","expected":"3","sample":false},{"input":"[5,10,15,20]","expected":"2","sample":false}]' WHERE title = 'Count Even Numbers in Array';

UPDATE problems SET test_cases = '[{"input":"[1,2,3,4,5]","expected":"3","sample":true},{"input":"[1,3,5,7]","expected":"4","sample":true},{"input":"[2,4,6]","expected":"0","sample":true},{"input":"[10]","expected":"0","sample":false},{"input":"[1]","expected":"1","sample":false},{"input":"[0]","expected":"0","sample":false},{"input":"[2,3,4,5]","expected":"2","sample":false},{"input":"[100,201,300]","expected":"1","sample":false},{"input":"[7,8,9,10]","expected":"2","sample":false},{"input":"[1,2,3,4,5,6,7,8]","expected":"4","sample":false},{"input":"[11,22,33,44,55]","expected":"3","sample":false},{"input":"[0,0,0]","expected":"0","sample":false},{"input":"[1,1,1]","expected":"3","sample":false},{"input":"[3,3,3]","expected":"3","sample":false},{"input":"[5,10,15,20]","expected":"2","sample":false}]' WHERE title = 'Count Odd Numbers';

UPDATE problems SET test_cases = '[{"input":"[1,2,3,4,5]","expected":"4","sample":true},{"input":"[10,20,30]","expected":"20","sample":true},{"input":"[5,5,5]","expected":"-1","sample":true},{"input":"[1,2]","expected":"1","sample":false},{"input":"[100,50,75]","expected":"75","sample":false},{"input":"[3,1,2]","expected":"2","sample":false},{"input":"[9,8,7,6]","expected":"8","sample":false},{"input":"[1,1,2]","expected":"1","sample":false},{"input":"[5,3,5,1]","expected":"3","sample":false},{"input":"[10,10,10]","expected":"-1","sample":false},{"input":"[7,7,8]","expected":"7","sample":false},{"input":"[1,3]","expected":"1","sample":false},{"input":"[50,40,30,20]","expected":"40","sample":false},{"input":"[99,100]","expected":"99","sample":false},{"input":"[2,4,6,8,10]","expected":"8","sample":false}]' WHERE title = 'Find Second Largest';

UPDATE problems SET test_cases = '[{"input":"[10,20,30]","expected":"20.0","sample":true},{"input":"[5,5,5]","expected":"5.0","sample":true},{"input":"[1,2,3,4]","expected":"2.5","sample":true},{"input":"[0]","expected":"0.0","sample":false},{"input":"[100]","expected":"100.0","sample":false},{"input":"[1,2]","expected":"1.5","sample":false},{"input":"[10,20]","expected":"15.0","sample":false},{"input":"[3,6,9]","expected":"6.0","sample":false},{"input":"[1,1,1,1]","expected":"1.0","sample":false},{"input":"[50,100]","expected":"75.0","sample":false},{"input":"[7,8,9]","expected":"8.0","sample":false},{"input":"[2,4,6,8,10]","expected":"6.0","sample":false},{"input":"[0,0,0]","expected":"0.0","sample":false},{"input":"[25,75]","expected":"50.0","sample":false},{"input":"[1,3,5,7,9]","expected":"5.0","sample":false}]' WHERE title = 'Find Average';

UPDATE problems SET test_cases = '[{"input":"[1,2,3,4,5]","expected":"True","sample":true},{"input":"[5,4,3,2,1]","expected":"False","sample":true},{"input":"[1]","expected":"True","sample":true},{"input":"[1,1,1]","expected":"True","sample":false},{"input":"[1,3,2]","expected":"False","sample":false},{"input":"[1,2]","expected":"True","sample":false},{"input":"[2,1]","expected":"False","sample":false},{"input":"[0,0,0,0]","expected":"True","sample":false},{"input":"[1,2,3]","expected":"True","sample":false},{"input":"[3,2,1]","expected":"False","sample":false},{"input":"[10,20,30,40]","expected":"True","sample":false},{"input":"[1,2,2,3]","expected":"True","sample":false},{"input":"[5,10,3]","expected":"False","sample":false},{"input":"[100,200,300]","expected":"True","sample":false},{"input":"[9,8]","expected":"False","sample":false}]' WHERE title = 'Check Sorted Array';

UPDATE problems SET test_cases = '[{"input":"[1,2,3]\\n[4,5,6]","expected":"[1, 2, 3, 4, 5, 6]","sample":true},{"input":"[1]\\n[2]","expected":"[1, 2]","sample":true},{"input":"[]\\n[1,2]","expected":"[1, 2]","sample":true},{"input":"[1,2]\\n[]","expected":"[1, 2]","sample":false},{"input":"[5,10]\\n[15,20]","expected":"[5, 10, 15, 20]","sample":false},{"input":"[0]\\n[0]","expected":"[0, 0]","sample":false},{"input":"[1,3,5]\\n[2,4,6]","expected":"[1, 3, 5, 2, 4, 6]","sample":false},{"input":"[100]\\n[200,300]","expected":"[100, 200, 300]","sample":false},{"input":"[7,8,9]\\n[10,11,12]","expected":"[7, 8, 9, 10, 11, 12]","sample":false},{"input":"[1,1]\\n[1,1]","expected":"[1, 1, 1, 1]","sample":false},{"input":"[-1]\\n[1]","expected":"[-1, 1]","sample":false},{"input":"[3,6]\\n[9,12]","expected":"[3, 6, 9, 12]","sample":false},{"input":"[50,60,70]\\n[80]","expected":"[50, 60, 70, 80]","sample":false},{"input":"[1,2,3,4]\\n[5,6,7,8]","expected":"[1, 2, 3, 4, 5, 6, 7, 8]","sample":false},{"input":"[10]\\n[20,30,40]","expected":"[10, 20, 30, 40]","sample":false}]' WHERE title = 'Merge Two Arrays';

UPDATE problems SET test_cases = '[{"input":"[1,2,2,3,3,4]","expected":"[1, 2, 3, 4]","sample":true},{"input":"[1,1,1]","expected":"[1]","sample":true},{"input":"[1,2,3]","expected":"[1, 2, 3]","sample":true},{"input":"[5]","expected":"[5]","sample":false},{"input":"[1,2,1,2]","expected":"[1, 2]","sample":false},{"input":"[3,3,3,3]","expected":"[3]","sample":false},{"input":"[10,20,10,30,20]","expected":"[10, 20, 30]","sample":false},{"input":"[0,0,1,1,2,2]","expected":"[0, 1, 2]","sample":false},{"input":"[5,4,3,2,1]","expected":"[5, 4, 3, 2, 1]","sample":false},{"input":"[7,7,8,8,9]","expected":"[7, 8, 9]","sample":false},{"input":"[1]","expected":"[1]","sample":false},{"input":"[2,2]","expected":"[2]","sample":false},{"input":"[100,200,100]","expected":"[100, 200]","sample":false},{"input":"[1,2,3,4,5]","expected":"[1, 2, 3, 4, 5]","sample":false},{"input":"[9,9,9,8,7]","expected":"[9, 8, 7]","sample":false}]' WHERE title = 'Remove Duplicates';

UPDATE problems SET test_cases = '[{"input":"[1,2,3,4,5]\\n3","expected":"2","sample":true},{"input":"[10,20,30]\\n20","expected":"1","sample":true},{"input":"[5,10,15]\\n5","expected":"0","sample":true},{"input":"[1,2,3]\\n4","expected":"-1","sample":false},{"input":"[7]\\n7","expected":"0","sample":false},{"input":"[1,2,3,4,5]\\n1","expected":"0","sample":false},{"input":"[1,2,3,4,5]\\n5","expected":"4","sample":false},{"input":"[10,20,30,40]\\n40","expected":"3","sample":false},{"input":"[100]\\n50","expected":"-1","sample":false},{"input":"[3,6,9,12]\\n9","expected":"2","sample":false},{"input":"[1,1,1]\\n1","expected":"0","sample":false},{"input":"[5,10,15,20]\\n15","expected":"2","sample":false},{"input":"[2,4,6,8,10]\\n6","expected":"2","sample":false},{"input":"[0,0,0]\\n0","expected":"0","sample":false},{"input":"[50,100]\\n100","expected":"1","sample":false}]' WHERE title = 'Find Index of Element';

UPDATE problems SET test_cases = '[{"input":"[1,2,2,3,3,3]\\n3","expected":"3","sample":true},{"input":"[1,1,1,1]\\n1","expected":"4","sample":true},{"input":"[5,10,15]\\n20","expected":"0","sample":true},{"input":"[0,0,0,0,0]\\n0","expected":"5","sample":false},{"input":"[1,2,3]\\n2","expected":"1","sample":false},{"input":"[7]\\n7","expected":"1","sample":false},{"input":"[1,2,3]\\n4","expected":"0","sample":false},{"input":"[5,5,5,5]\\n5","expected":"4","sample":false},{"input":"[10,20,10,30,10]\\n10","expected":"3","sample":false},{"input":"[1,2,1,2,1]\\n1","expected":"3","sample":false},{"input":"[3,3,3]\\n3","expected":"3","sample":false},{"input":"[100,200,300]\\n200","expected":"1","sample":false},{"input":"[1]\\n1","expected":"1","sample":false},{"input":"[1]\\n2","expected":"0","sample":false},{"input":"[2,4,6,8,2]\\n2","expected":"2","sample":false}]' WHERE title = 'Count Occurrences';

UPDATE problems SET test_cases = '[{"input":"[1,2,3,4]","expected":"24","sample":true},{"input":"[5,5]","expected":"25","sample":true},{"input":"[1]","expected":"1","sample":true},{"input":"[2,3]","expected":"6","sample":false},{"input":"[10,10,10]","expected":"1000","sample":false},{"input":"[0,5,10]","expected":"0","sample":false},{"input":"[1,1,1,1]","expected":"1","sample":false},{"input":"[2,2,2]","expected":"8","sample":false},{"input":"[3,3,3]","expected":"27","sample":false},{"input":"[7,1]","expected":"7","sample":false},{"input":"[100]","expected":"100","sample":false},{"input":"[5,4,3,2,1]","expected":"120","sample":false},{"input":"[2,5]","expected":"10","sample":false},{"input":"[6,7]","expected":"42","sample":false},{"input":"[1,2,3,4,5]","expected":"120","sample":false}]' WHERE title = 'Multiply All Elements';

UPDATE problems SET test_cases = '[{"input":"5","expected":"Positive","sample":true},{"input":"-3","expected":"Negative","sample":true},{"input":"0","expected":"Zero","sample":true},{"input":"1","expected":"Positive","sample":false},{"input":"-1","expected":"Negative","sample":false},{"input":"100","expected":"Positive","sample":false},{"input":"-100","expected":"Negative","sample":false},{"input":"42","expected":"Positive","sample":false},{"input":"-42","expected":"Negative","sample":false},{"input":"999","expected":"Positive","sample":false},{"input":"-999","expected":"Negative","sample":false},{"input":"7","expected":"Positive","sample":false},{"input":"-7","expected":"Negative","sample":false},{"input":"50","expected":"Positive","sample":false},{"input":"-50","expected":"Negative","sample":false}]' WHERE title = 'Check Positive or Negative';

UPDATE problems SET test_cases = '[{"input":"listen\\nsilent","expected":"True","sample":true},{"input":"hello\\nworld","expected":"False","sample":true},{"input":"abc\\ncba","expected":"True","sample":true},{"input":"a\\na","expected":"True","sample":false},{"input":"ab\\nba","expected":"True","sample":false},{"input":"abc\\nabd","expected":"False","sample":false},{"input":"rat\\ntar","expected":"True","sample":false},{"input":"cat\\nact","expected":"True","sample":false},{"input":"dog\\ngod","expected":"True","sample":false},{"input":"test\\ntset","expected":"True","sample":false},{"input":"ab\\nab","expected":"True","sample":false},{"input":"abc\\ndef","expected":"False","sample":false},{"input":"aabb\\nbbaa","expected":"True","sample":false},{"input":"xyz\\nxzy","expected":"True","sample":false},{"input":"hello\\nhellp","expected":"False","sample":false}]' WHERE title = 'Check Anagram';

UPDATE problems SET test_cases = '[{"input":"hello world\\nworld","expected":"True","sample":true},{"input":"python\\njava","expected":"False","sample":true},{"input":"abc\\na","expected":"True","sample":true},{"input":"test\\ntest","expected":"True","sample":false},{"input":"abc\\nd","expected":"False","sample":false},{"input":"programming\\ngram","expected":"True","sample":false},{"input":"hello\\nlo","expected":"True","sample":false},{"input":"data\\ndat","expected":"True","sample":false},{"input":"code\\nxyz","expected":"False","sample":false},{"input":"abcdef\\ncde","expected":"True","sample":false},{"input":"hello\\nhello world","expected":"False","sample":false},{"input":"string\\nring","expected":"True","sample":false},{"input":"test\\nesting","expected":"False","sample":false},{"input":"abcabc\\nabc","expected":"True","sample":false},{"input":"xyz\\nxyz","expected":"True","sample":false}]' WHERE title = 'Check Substring';

UPDATE problems SET test_cases = '[{"input":"hello\\nl","expected":"2","sample":true},{"input":"aabbcc\\na","expected":"2","sample":true},{"input":"test\\nt","expected":"2","sample":true},{"input":"abc\\nd","expected":"0","sample":false},{"input":"aaaa\\na","expected":"4","sample":false},{"input":"hello\\no","expected":"1","sample":false},{"input":"programming\\nm","expected":"2","sample":false},{"input":"banana\\na","expected":"3","sample":false},{"input":"mississippi\\ns","expected":"4","sample":false},{"input":"hello\\nh","expected":"1","sample":false},{"input":"aeiou\\ne","expected":"1","sample":false},{"input":"xxx\\nx","expected":"3","sample":false},{"input":"abc\\na","expected":"1","sample":false},{"input":"abcabc\\nc","expected":"2","sample":false},{"input":"zzz\\nz","expected":"3","sample":false}]' WHERE title = 'Count Character Frequency';

UPDATE problems SET test_cases = '[{"input":"hello world","expected":"helloworld","sample":true},{"input":"a b c","expected":"abc","sample":true},{"input":"no spaces","expected":"nospaces","sample":true},{"input":"hello","expected":"hello","sample":false},{"input":"  leading","expected":"leading","sample":false},{"input":"trailing  ","expected":"trailing","sample":false},{"input":"  both  ","expected":"both","sample":false},{"input":"a  b  c","expected":"abc","sample":false},{"input":"one two three","expected":"onetwothree","sample":false},{"input":"x y z","expected":"xyz","sample":false},{"input":"hi there","expected":"hithere","sample":false},{"input":"test case","expected":"testcase","sample":false},{"input":"no  extra  space","expected":"noextraspace","sample":false},{"input":"a","expected":"a","sample":false},{"input":"  a  ","expected":"a","sample":false}]' WHERE title = 'Remove Spaces From String';

UPDATE problems SET test_cases = '[{"input":"hello","expected":"h","sample":true},{"input":"world","expected":"w","sample":true},{"input":"a","expected":"a","sample":true},{"input":"Python","expected":"P","sample":false},{"input":"Java","expected":"J","sample":false},{"input":"code","expected":"c","sample":false},{"input":"test","expected":"t","sample":false},{"input":"xyz","expected":"x","sample":false},{"input":"ABC","expected":"A","sample":false},{"input":"123","expected":"1","sample":false},{"input":"Z","expected":"Z","sample":false},{"input":"open","expected":"o","sample":false},{"input":"data","expected":"d","sample":false},{"input":"fun","expected":"f","sample":false},{"input":"hi","expected":"h","sample":false}]' WHERE title = 'First Character';

UPDATE problems SET test_cases = '[{"input":"hello","expected":"o","sample":true},{"input":"world","expected":"d","sample":true},{"input":"a","expected":"a","sample":true},{"input":"Python","expected":"n","sample":false},{"input":"Java","expected":"a","sample":false},{"input":"code","expected":"e","sample":false},{"input":"test","expected":"t","sample":false},{"input":"xyz","expected":"z","sample":false},{"input":"ABC","expected":"C","sample":false},{"input":"123","expected":"3","sample":false},{"input":"Z","expected":"Z","sample":false},{"input":"open","expected":"n","sample":false},{"input":"data","expected":"a","sample":false},{"input":"fun","expected":"n","sample":false},{"input":"hi","expected":"i","sample":false}]' WHERE title = 'Last Character';

UPDATE problems SET test_cases = '[{"input":"hello world","expected":"1","sample":true},{"input":"a b c d","expected":"3","sample":true},{"input":"nospaces","expected":"0","sample":true},{"input":" ","expected":"1","sample":false},{"input":"  ","expected":"2","sample":false},{"input":"one two three","expected":"2","sample":false},{"input":"a","expected":"0","sample":false},{"input":"hello  world","expected":"2","sample":false},{"input":"test case here","expected":"2","sample":false},{"input":"   three   ","expected":"6","sample":false},{"input":"hi there","expected":"1","sample":false},{"input":"abc","expected":"0","sample":false},{"input":"x y","expected":"1","sample":false},{"input":"a b c d e","expected":"4","sample":false},{"input":"single","expected":"0","sample":false}]' WHERE title = 'Count Spaces in String';

UPDATE problems SET test_cases = '[{"input":"hello\\nl","expected":"heo","sample":true},{"input":"world\\no","expected":"wrld","sample":true},{"input":"abc\\nb","expected":"ac","sample":true},{"input":"test\\nt","expected":"es","sample":false},{"input":"aaa\\na","expected":"","sample":false},{"input":"python\\np","expected":"ython","sample":false},{"input":"hello\\nx","expected":"hello","sample":false},{"input":"abcabc\\nc","expected":"abab","sample":false},{"input":"programming\\ng","expected":"prorammin","sample":false},{"input":"remove\\ne","expected":"rmov","sample":false},{"input":"data\\na","expected":"dt","sample":false},{"input":"coding\\nd","expected":"coing","sample":false},{"input":"xyz\\nz","expected":"xy","sample":false},{"input":"aeiou\\na","expected":"eiou","sample":false},{"input":"mississippi\\ni","expected":"msssspp","sample":false}]' WHERE title = 'Remove Character From String';

UPDATE problems SET test_cases = '[{"input":"hello\\nl\\nx","expected":"hexxo","sample":true},{"input":"world\\no\\na","expected":"warld","sample":true},{"input":"abc\\nb\\nz","expected":"azc","sample":true},{"input":"test\\nt\\nm","expected":"mesm","sample":false},{"input":"aaa\\na\\nb","expected":"bbb","sample":false},{"input":"python\\np\\nP","expected":"Python","sample":false},{"input":"hello\\nx\\ny","expected":"hello","sample":false},{"input":"abcabc\\nc\\nz","expected":"abzabz","sample":false},{"input":"data\\na\\no","expected":"doto","sample":false},{"input":"code\\ne\\na","expected":"coda","sample":false},{"input":"xyz\\nx\\na","expected":"ayz","sample":false},{"input":"aba\\na\\nc","expected":"cbc","sample":false},{"input":"test\\ne\\na","expected":"tast","sample":false},{"input":"noon\\nn\\nm","expected":"moom","sample":false},{"input":"deed\\nd\\nb","expected":"beeb","sample":false}]' WHERE title = 'Replace Character';
